<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <input type="hidden" name="id" value="<?= $params['id']; ?>"/>

	    <p class="msg-atencao"><?php printf(TXT_DIVERSOS_AVISO_USUARIO_RESET_SENHA, $params['nome-usuario']); ?></p>

        <p class="form-paragr">
            <label for="txt-senha-nova" class="form-rotulo"><?= TXT_ROTULO_SENHA_NOVA; ?>:</label><br/>
            <input type="password" name="senha_nova" id="txt-senha-nova" class="form-controle" required/>
        </p>

        <p class="form-paragr">
            <label for="txt-senha-conf" class="form-rotulo"><?= TXT_ROTULO_SENHA_CONF; ?>:</label><br/>
            <input type="password" name="senha_nova_conf" id="txt-senha-conf" class="form-controle" required/>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]
