<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <p class="form-paragr">
	        <?= $this->aux_form->_campo_geral('texto', 'login', 'login', $mod->login, TXT_ROTULO_LOGIN, null, ['required' => 'required']); ?>
        </p>

        <p class="form-paragr">
	        <?= $this->aux_form->_campo_geral('senha', 'senha', 'senha', $mod->senha, TXT_ROTULO_SENHA, null, ['required' => 'required']); ?>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-entrar"><?= TXT_BOTAO_ENTRAR; ?></button>

            <a href="login/esqueci-minha-senha" class="com-icone ico-duvida ico-esqueci-senha">
                <?= TXT_LINK_ESQUECI_MINHA_SENHA; ?>
            </a>
        </p>
    </form>
[/DL3-CONTEUDO]