<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
        <p class="form-paragr">
	        <?php echo $this->aux_form->_campo_geral('texto', 'login', 'login', $mod->login, TXT_ROTULO_LOGIN_OU_EMAIL, null, ['required' => 'required']); ?>
        </p>

        <p class="form-botoes">
            <?php echo $this->aux_form->_botao('enviar-email', TXT_BOTAO_ENVIAR); ?>

            <a href="javascript:" class="com-icone ico-voltar" onclick="history.back();">
                <?php echo TXT_LINK_VOLTAR; ?>
            </a>
        </p>
    </form>
[/DL3-CONTEUDO]