<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
        <input type="hidden" name="id" value="<?php echo $params['id']; ?>"/>

	    <p class="msg-atencao"><?php printf(TXT_DIVERSOS_AVISO_USUARIO_RESET_SENHA, $params['nome-usuario']); ?></p>

        <p class="form-paragr">
            <?php echo $this->aux_form->_campo_geral('senha', 'senha_nova', 'senha-nova', null, TXT_ROTULO_SENHA_NOVA, null, ['required' => 'required']); ?>
        </p>

        <p class="form-paragr">
	        <?php echo $this->aux_form->_campo_geral('senha', 'senha_nova_conf', 'senha-conf', null, TXT_ROTULO_SENHA_CONF, null, ['required' => 'required']); ?>
        </p>

        <p class="form-botoes">
	        <?php
	        echo $this->aux_form->_botao('salvar', TXT_BOTAO_SALVAR);
	        echo $this->aux_form->_botao('cancelar', TXT_BOTAO_CANCELAR);
	        ?>
        </p>
    </form>
[/DL3-CONTEUDO]
