<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) )
    $params = $this->_obterparams();

$mod = $params['modelo'];

?>

<section class="dl3-conteudo">
    <h1 class="titulo-h1"><?= $params['titulo']; ?></h1>

    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <p class="form-paragr">
            <label for="txt-login" class="form-rotulo"><?= TXT_ROTULO_LOGIN_OU_EMAIL; ?>:</label><br/>
            <input type="text" name="login" id="txt-login" class="form-controle" required/>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-enviar"><?= TXT_BOTAO_ENVIAR; ?></button>

            <a href="javascript:;" class="com-icone ico-voltar" onclick="history.back();">
                <?= TXT_LINK_VOLTAR; ?>
            </a>
        </p>
    </form>
</section>