<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 14:18:37
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php if( $mod->historia != '' ): ?>
    <h2 class="titulo-h2"><?= TXT_PAGINA_TITULO_HISTORIA; ?></h2>
    <p class="instit-historia"><?= nl2br($mod->historia); ?></p>
    <?php endif;

    if( $mod->missao != '' ): ?>
    <h2 class="titulo-h2"><?= TXT_PAGINA_TITULO_MISSAO; ?></h2>
    <p class="instit-missao"><?= nl2br($mod->missao); ?></p>
    <?php endif;

    if( $mod->visao != '' ): ?>
    <h2 class="titulo-h2"><?= TXT_PAGINA_TITULO_VISAO; ?></h2>
    <p class="instit-visao"><?= nl2br($mod->visao); ?></p>
    <?php endif;

    if( $mod->valores != '' ): ?>
    <h2 class="titulo-h2"><?= TXT_PAGINA_TITULO_VALORES; ?></h2>
    <p class="instit-valores"><?= nl2br($mod->valores); ?></p>
    <?php endif; ?>
[/DL3-CONTEUDO]