<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 04/03/2015 19:39:25
 */

!isset($params) AND $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <p>
        <a href="website/institucional/editar" class="com-icone ico-editar">
            <?= TXT_LINK_EDITAR_INFOS_INSTITUCIONAIS; ?>
        </a>
    </p>

    <details class="detalhes" open>
        <summary class="det-titulo"><?= TXT_PAGINA_TITULO_HISTORIA; ?></summary>
        <p><?= nl2br($mod->historia); ?></p>
    </details>

    <details class="detalhes" open>
        <summary class="det-titulo"><?= TXT_PAGINA_TITULO_MISSAO; ?></summary>
        <p><?= nl2br($mod->missao); ?></p>
    </details>

    <details class="detalhes" open>
        <summary class="det-titulo"><?= TXT_PAGINA_TITULO_VISAO; ?></summary>
        <p><?= nl2br($mod->visao); ?></p>
    </details>

    <details class="detalhes" open>
        <summary class="det-titulo"><?= TXT_PAGINA_TITULO_VALORES; ?></summary>
        <p><?= nl2br($mod->valores); ?></p>
    </details>
[/DL3-CONTEUDO]