<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>

        <p class="msg-info"><?php echo TXT_DIVERSOS_CONFIGURACAO_WEBSITE; ?></p>

        <p class="form-paragr">
            <?php echo $this->aux_form->_combo_select('tema', 'tema', $mod->tema, TXT_ROTULO_TEMA, null, ['required' => 'required'],
                array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], $params['temas'])
            ); ?>
        </p>

        <p class="form-paragr">
	        <?php echo $this->aux_form->_combo_select('formato_data', 'formato_data', $mod->formato_data, TXT_ROTULO_FORMATO_DATA, null, ['required' => 'required'],
		        array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], $params['formatos-data'])
	        ); ?>
        </p>

        <p class="form-botoes">
            <?php
            echo $this->aux_form->_botao('salvar', TXT_BOTAO_SALVAR);
            echo $this->aux_form->_botao('cancelar', TXT_BOTAO_CANCELAR);
			?>
        </p>
    </form>
[/DL3-CONTEUDO]