<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) )
    $params = $this->_obterparams();

$mod = $params['modelo'];

?>

<section class="dl3">
    <h1><?= $params['titulo']; ?></h1>

    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>" enctype="multipart/form-data">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset>
            <legend><?= TXT_LEGENDA_TIPO_DADO; ?></legend>

            <p class="form-p-campo">
                <label for="txt-descr"><?= TXT_LABEL_DESCR; ?>:</label><br/>
                <input type="text" name="descr" id="txt-descr" value="<?= $mod->descr; ?>" required/>
            </p>

            <p class="form-p-campo">
                <label for="arq-icone"><?= TXT_LABEL_ICONE; ?>:</label><br/>
                <input type="file" name="icone" id="arq-icone"/>

                <?php if( $mod->icone != '' ): ?>
                <figure class="mostrar-icone">
                    <img src="..<?= $mod->icone; ?>" alt=""/>
                </figure>
                <?php endif; ?>
            </p>

            <p class="form-p-campo">
                <label><?= TXT_LABEL_REDE_SOCIAL; ?></label><br/>
                <input type="checkbox" name="rede_social" id="rede-social" class="s-ou-n" value="1"<?= $mod->rede_social ? ' CHECKED' : ''; ?>/>
                <label for="rede-social"></label>
            </p>
        </fieldset>

        <fieldset>
            <legend><?= TXT_LEGENDA_OPCOES_AVANCADAS; ?></legend>

            <p class="form-p-campo">
                <label for="txt-mascara"><?= TXT_LABEL_MASCARA; ?>:</label><br/>
                <span class="form-dica"><?= TXT_DICA_TIPODADO_MASCARA; ?></span><br/>
                <input type="text" name="mascara" id="txt-mascara" value="<?= $mod->mascara; ?>"/>
            </p>

            <p class="form-p-campo">
                <label for="txt-expreg"><?= TXT_LABEL_EXPREG; ?>:</label><br/>
                <span class="form-dica"><?= TXT_DICA_TIPODADO_EXPREG; ?></span><br/>
                <input type="text" name="expreg" id="txt-expreg" value="<?= $mod->expreg; ?>"/>
            </p>
        </fieldset>

        <p class="form-p-campo">
            <label><?= TXT_LABEL_PUBLICAR; ?></label><br/>
            <input type="checkbox" name="publicar" id="chk-publicar" class="s-ou-n" value="1"<?= $mod->publicar || $params['incluindo'] ? ' CHECKED' : ''; ?>/>
            <label for="chk-publicar"></label>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
</section>
