<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) )
    $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>" enctype="multipart/form-data">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_TIPO_DADO; ?></legend>

            <p class="form-paragr">
                <label for="txt-descr" class="form-rotulo"><?= TXT_ROTULO_DESCR; ?>:</label><br/>
                <input type="text" name="descr" id="txt-descr" value="<?= $mod->descr; ?>" class="form-controle" required/>
            </p>

            <p class="form-paragr">
                <label for="arq-icone" class="form-rotulo"><?= TXT_ROTULO_ICONE; ?>:</label><br/>
                <input type="file" name="icone" id="arq-icone" class="form-controle"/>

                <?php if( $mod->icone != '' ): ?>
                <figure class="mostrar-icone">
                    <img src="..<?= $mod->icone; ?>" alt=""/>
                </figure>
                <?php endif; ?>
            </p>

            <p class="form-paragr">
                <span class="form-rotulo"><?= TXT_ROTULO_REDE_SOCIAL; ?></span><br/>
                <input type="checkbox" name="rede_social" id="rede-social" class="form-alternar"<?= $mod->rede_social ? ' CHECKED' : ''; ?>/>
                <label for="rede-social"></label>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_OPCOES_AVANCADAS; ?></legend>

            <p class="form-paragr">
                <label for="txt-mascara" class="form-rotulo"><?= TXT_ROTULO_MASCARA; ?>:</label><br/>
                <span class="form-dica"><?= TXT_DICA_TIPODADO_MASCARA; ?></span><br/>
                <input type="text" name="mascara" id="txt-mascara" value="<?= $mod->mascara; ?>" class="form-controle"/>
            </p>

            <p class="form-paragr">
                <label for="txt-expreg" class="form-rotulo"><?= TXT_ROTULO_EXPREG; ?>:</label><br/>
                <span class="form-dica"><?= TXT_DICA_TIPODADO_EXPREG; ?></span><br/>
                <input type="text" name="expreg" id="txt-expreg" value="<?= $mod->expreg; ?>" class="form-controle"/>
            </p>
        </fieldset>

        <p class="form-paragr">
            <span class="form-rotulo"><?= TXT_ROTULO_PUBLICAR; ?></span><br/>
            <input type="checkbox" name="publicar" id="chk-publicar" class="form-alternar"<?= $mod->publicar ? ' CHECKED' : ''; ?>/>
            <label for="chk-publicar"></label>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]
