<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

/*
 * TAREFA: incluir ou criar editores HTML para os textareas
 */

!isset($params) AND $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_HISTORIA; ?></legend>

            <p class="form-paragr">
                <textarea name="historia" class="form-controle form-textarea"><?= $mod->historia; ?></textarea>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_MISSAO; ?></legend>

            <p class="form-paragr">
                <textarea name="missao" class="form-controle form-textarea"><?= $mod->missao; ?></textarea>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_VISAO; ?></legend>

            <p class="form-paragr">
                <textarea name="visao" class="form-controle form-textarea"><?= $mod->visao; ?></textarea>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_VALORES; ?></legend>

            <p class="form-paragr">
                <textarea name="valores" class="form-controle form-textarea"><?= $mod->valores; ?></textarea>
            </p>
        </fieldset>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]