<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <p class="msg-info"><?= TXT_AJUDA_CONFIGURACAO_WEBSITE; ?></p>

        <p class="form-paragr">
            <?= $this->aux_form->_combo_select('tema', 'tema', $mod->tema, TXT_ROTULO_TEMA, null, ['required' => 'required'],
                array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], $params['temas'])
            ); ?>
        </p>

        <p class="form-paragr">
	        <?= $this->aux_form->_combo_select('formato_data', 'formato_data', $mod->formato_data, TXT_ROTULO_FORMATO_DATA, null, ['required' => 'required'],
		        array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], $params['formatos-data'])
	        ); ?>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]