<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>"<?php $params['incluindo'] and print(' enctype="multipart/form-data"');?>>
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_ALBUM_FOTOS; ?></legend>

            <p class="form-paragr">
                <?= $this->aux_form->_campo_geral('texto', 'nome', 'nome', $mod->nome, TXT_ROTULO_NOME, null, ['required' => 'required']); ?>
            </p>

            <?php if( $params['incluindo'] ): ?>
            <p class="form-paragr">
	            <?= $this->aux_form->_arquivo_upload('fotos[]', 'arq-fotos', TXT_ROTULO_FOTOS, ['multiple' => 'multiple'], $params['extensoes']); ?>
            </p>
            <?php endif; ?>

	        <p class="form-paragr">
		        <?= $this->aux_form->_chk_sim_nao('publicar', 'chk-publicar', TXT_ROTULO_PUBLICAR, TXT_DICA_PUBLICAR_REGISTRO, $mod->publicar ? 'CHECKED' : ''); ?>
	        </p>
        </fieldset>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>

    <?php if( !$params['incluindo'] ): ?>
    <form id="form-fotos" method="post" action="website/albuns-de-fotos/incluir-fotos" enctype="multipart/form-data" class="form-upload-simples">
        <input type="hidden" name="foto_album" value="<?= $mod->id; ?>"/>

        <fieldset class="form-grupo">
            <legend class="form-legenda">
	            <?= TXT_LEGENDA_FOTOS; ?>

	            <span class="log-registro">
		            (<?php switch($params['qtde-fotos']){
			            case 0: echo TXT_DIVERSOS_NENHUMA_FOTO; break;
			            case 1: echo TXT_DIVERSOS_UMA_FOTO; break;
			            default: printf(TXT_DIVERSOS_QTDE_FOTOS, $params['qtde-fotos']);
		            } ?>)
	            </span>
            </legend>


            <span class="form-paragr">
                <?= $this->aux_form->_arquivo_upload('fotos[]', 'arq-fotos', TXT_ROTULO_FOTOS, ['multiple' => 'multiple'], $params['extensoes']); ?>
            </span>

	        <span class="form-botoes" style="margin-left: .5em;">
		        <button type="submit" class="btn-upload"><?= TXT_BOTAO_SALVAR_FOTOS; ?></button>
	        </span>
        </fieldset>
    </form>

    <form id="form-remover-fotos" method="post" action="website/albuns-de-fotos/excluir-fotos" class="mostrar-fotos flexivel">
        <?php foreach( $params['fotos'] as $f ): ?>
        <figure class="album-foto col-4">
            <img src="..<?= $f['foto_album_imagem']; ?>" class="af-imagem" alt=""/>

            <figcaption class="af-infos">
                <p>
                    <?php if( !empty($f['foto_album_titulo']) ):
                        echo TXT_ROTULO_TITULO, ": {$f['foto_album_titulo']}<br/>";
                    endif;

                    if( !empty($f['foto_album_descr']) ):
                        echo TXT_ROTULO_DESCR, ': ', nl2br($f['foto_album_descr']);
                    endif; ?>
                </p>

                <p class="af-links">
                    <?php if( $f['foto_album_capa'] == 1 ): ?>
                    <span class="af-capa"><?= MSG_CAPA; ?></span>
                    <?php endif; ?>

                    <a href="javascript:;" onclick="CarregarForm('website/albuns-de-fotos/editar-foto/<?= $f['foto_album_id']; ?>', function(){ return true; }, function(){ window.location.reload(); });" class="so-icone ico-editar" title="<?= TXT_LINK_TITLE_EDITAR;?>">
                        <?= TXT_LINK_EDITAR; ?>
                    </a>

                    <label for="id-foto-<?= $f['foto_album_id']; ?>" class="so-icone ico-remover" style="display:inline;"></label>
                    <input type="checkbox" name="id[]" id="id-foto-<?= $f['foto_album_id']; ?>" value="<?= $f['foto_album_id']; ?>"
                           style="visibility: hidden; width: 0;" onchange="$fr.submit();"/>
                </p>
            </figcaption>
        </figure>
        <?php endforeach; ?>
    </form>
    <?php endif; ?>
[/DL3-CONTEUDO]

<?php if( !$params['incluindo'] ): ?>
[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $ff = $('#form-fotos')._formulario({
        depois: function(){
            window.location.reload();
        },
        aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: 'formulario' }
    });

    $fr = $('#form-remover-fotos')._formulario({
        depois: function(){
            window.location.reload();
        },
        aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: 'formulario' }
    });
    //]]>
</script>
[/DL3-SCRIPTS]
<?php endif; ?>