<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) )
    $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>" enctype="multipart/form-data">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_ALBUM_FOTOS; ?></legend>

            <p class="form-paragr">
                <label for="txt-nome" class="form-rotulo"><?= TXT_ROTULO_NOME; ?>:</label><br/>
                <input type="text" name="nome" id="txt-nome" value="<?= $mod->nome; ?>" class="form-controle" required/>
            </p>

            <?php if( $params['incluindo'] ): ?>
            <p class="form-paragr">
                <label for="arq-fotos" class="form-rotulo"><?= TXT_ROTULO_FOTOS; ?>:</label><br/>
                <input type="file" name="fotos" id="arq-fotos" class="form-controle" multiple/>
            </p>
            <?php endif; ?>

            <p class="form-paragr">
                <span class="form-rotulo"><?= TXT_ROTULO_PUBLICAR; ?></span><br/>
                <input type="checkbox" name="publicar" id="chk-publicar" class="form-alternar"<?= $mod->publicar ? ' CHECKED' : ''; ?>/>
                <label for="chk-publicar"></label>
            </p>
        </fieldset>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>

    <?php if( !$params['incluindo'] ): ?>
    <form id="form-fotos" method="post" action="website/albuns-de-fotos/incluir-fotos" enctype="multipart/form-data" class="form-upload-simples">
        <input type="hidden" name="foto_album" value="<?= $mod->id; ?>"/>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_FOTOS; ?></legend>

            <p class="form-paragr">
                <label for="arq-fotos" class="form-rotulo"><?= TXT_ROTULO_FOTOS; ?>:</label><br/>
                <input type="file" name="fotos[]" id="arq-fotos" class="form-controle" multiple required/>
            </p>
        </fieldset>

        <p class="form-botoes">
            <button type="submit" class="btn-upload"><?= TXT_BOTAO_SALVAR_FOTOS; ?></button>
        </p>
    </form>

    <form id="form-remover-fotos" method="post" action="website/albuns-de-fotos/excluir-fotos" class="mostrar-fotos flexivel">
        <?php foreach( $params['fotos'] as $f ): ?>
        <figure class="album-foto col-4">
            <img src="..<?= $f['foto_album_imagem']; ?>" class="af-imagem" alt=""/>

            <figcaption class="af-infos">
                <p>
                    <?php if( !empty($f['foto_album_titulo']) ):
                        echo TXT_ROTULO_TITULO, ": {$f['foto_album_titulo']}<br/>";
                    endif;

                    if( !empty($f['foto_album_descr']) ):
                        echo TXT_ROTULO_DESCR, ': ', nl2br($f['foto_album_descr']);
                    endif; ?>
                </p>

                <p class="af-links">
                    <?php if( $f['foto_album_capa'] == 1 ): ?>
                    <span class="af-capa"><?= MSG_CAPA; ?></span>
                    <?php endif; ?>

                    <a href="javascript:;" onclick="CarregarForm('website/albuns-de-fotos/editar-foto/<?= $f['foto_album_id']; ?>');" class="so-icone ico-editar" title="<?= TXT_LINK_TITLE_EDITAR;?>">
                        <?= TXT_LINK_EDITAR; ?>
                    </a>

                    <label for="id-foto-<?= $f['foto_album_id']; ?>" class="so-icone ico-remover" style="display:inline;"></label>
                    <input type="checkbox" name="id[]" id="id-foto-<?= $f['foto_album_id']; ?>" value="<?= $f['foto_album_id']; ?>"
                           style="visibility: hidden; width: 0;" onchange="$fr.submit();"/>
                </p>
            </figcaption>
        </figure>
        <?php endforeach; ?>
    </form>
    <?php endif; ?>
[/DL3-CONTEUDO]

<?php if( !$params['incluindo'] ): ?>
[DL3-SCRIPTS]
<script>
    //<![CDATA[
    window.addEventListener('load', function(){
        $ff = $('#form-fotos')._dlformulario({
            depois: function(){
                window.location.reload();
            },
            aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: 'formulario' }
        });

        $fr = $('#form-remover-fotos')._dlformulario({
            depois: function(){
                window.location.reload();
            },
            aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: 'formulario' }
        });
    });
    //]]>
</script>
[/DL3-SCRIPTS]
<?php endif; ?>