<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) )
    $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <p class="form-paragr">
	        <?= $this->aux_form->_combo_select('tipo', 'tipo', $mod->tipo, TXT_ROTULO_TIPO, null, ['required' => 'required'],
		        array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], $params['tipos'])
	        ); ?>

            <?php if( $params['novo-tipo?'] ): ?>
            <a href="javascript:;" onclick="CarregarForm('website/tipos-de-dados/novo', null, function(){ CarregarSelect($('#sel-tipo'), 'website/tipos-de-dados/carregar-select'); });" class="com-icone ico-inserir">
                <?= TXT_LINK_NOVO_TIPO_DADO; ?>
            </a>
            <?php endif; ?>
        </p>

        <p class="form-paragr">
            <?= $this->aux_form->_campo_geral('texto', 'descr', 'descr', $mod->descr, TXT_ROTULO_DESCR, null, [
	            'pattern' => isset($params['expreg']) ? $params['expreg'] : null,
                'required' => 'required'
            ]); ?>
        </p>

        <p class="form-paragr">
	        <?= $this->aux_form->_chk_sim_nao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    <?php if( !empty($params['mascara']) ): ?>
    // Aplicar a máscara
    $('#txt-descr')._mascara('<?= $params['mascara']; ?>');
    <?php endif; ?>

    $('#sel-tipo').on('change', function(){
        var tipo = $(this).val();

        $.ajax({
            url     : 'website/tipos-de-dados/opcoes-avancadas',
            type    : 'post',
            dataType: 'json',
            data    : 'id='+ tipo,
            success : function(j){
                var $descr = $('#txt-descr');

                if( j.mascara != '' )
                    $descr._mascara(j.mascara);

                if( j.expreg != '' )
                    $descr.attr({ pattern: j.expreg });
            }
        });
    });
    //]]>
</script>
[/DL3-SCRIPTS]
