<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) )
    $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <p class="form-paragr">
            <label for="sel-tipo" class="form-rotulo"><?= TXT_ROTULO_TIPO; ?>:</label><br/>
            <select name="tipo" id="sel-tipo" class="form-controle" required>
                <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>

                <?php foreach( $params['tipos'] as $o ): ?>
                <option value="<?= $o['VALOR']; ?>"<?= $o['VALOR'] == $mod->tipo ? ' SELECTED' : ''; ?>>
                    <?= $o['TEXTO']; ?>
                </option>
                <?php endforeach; ?>
            </select>

            <?php if( $params['novo-tipo?'] ): ?>
            <a href="javascript:;" onclick="CarregarForm('website/tipos-de-dados/novo', null, function(){ CarregarSelect($('#sel-tipo'), 'website/tipos-de-dados/carregar-select'); });" class="com-icone ico-inserir">
                <?= TXT_LINK_NOVO_TIPO_DADO; ?>
            </a>
            <?php endif; ?>
        </p>

        <p class="form-paragr">
            <label for="txt-descr" class="form-rotulo"><?= TXT_ROTULO_DESCR; ?>:</label><br/>
            <input type="text" name="descr" id="txt-descr" value="<?= $mod->descr; ?>"<?php !empty($params['expreg']) and print(' pattern="'. $params['expreg'] .'"'); ?> class="form-controle" required/>
        </p>

        <p class="form-paragr">
            <span class="form-rotulo"><?= TXT_ROTULO_PUBLICAR; ?></span><br/>
            <input type="checkbox" name="publicar" id="chk-publicar" class="form-alternar"<?php $mod->publicar and print(' CHECKED'); ?>/>
            <label for="chk-publicar"></label>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    <?php if( !empty($params['mascara']) ): ?>
    // Aplicar a máscara
    $('#txt-descr')._mascara('<?= $params['mascara']; ?>');
    <?php endif; ?>

    $('#sel-tipo').on('change', function(){
        var tipo = $(this).val();

        $.ajax({
            url     : 'website/tipos-de-dados/opcoes-avancadas',
            type    : 'post',
            dataType: 'json',
            data    : 'id='+ tipo,
            success : function(j){
                var $descr = $('#txt-descr');

                if( j.mascara != '' )
                    $descr._mascara(j.mascara);

                if( j.expreg != '' )
                    $descr.attr({ pattern: j.expreg });
            }
        });
    });
    //]]>
</script>
[/DL3-SCRIPTS]
