<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) AND $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <p class="msg-info"><?= TXT_AJUDA_CONFIGURACAO_WEBSITE; ?></p>

        <p class="form-paragr">
            <label for="sel-tema" class="form-rotulo"><?= TXT_ROTULO_TEMA; ?>:</label><br/>
            <select name="tema" id="sel-tema" class="form-controle" required>
                <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>

                <?php foreach( $params['temas'] as $o ): ?>
                <option value="<?= $o['VALOR']; ?>"<?php $o['VALOR'] == $mod->tema AND print(' SELECTED'); ?>>
                    <?= $o['TEXTO']; ?>
                </option>
                <?php endforeach; ?>
            </select>
        </p>

        <p class="form-paragr">
            <label for="formato-data" class="form-rotulo"><?= TXT_ROTULO_FORMATO_DATA; ?>:</label><br/>
            <select name="formato_data" id="formato-data" class="form-controle" required>
                <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>

                <?php foreach( $params['formatos-data'] as $o ): ?>
                <option value="<?= $o['VALOR']; ?>"<?php $o['VALOR'] == $mod->formato_data AND print(' SELECTED'); ?>>
                    <?= $o['TEXTO']; ?>
                </option>
                <?php endforeach; ?>
            </select>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]