<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <input type="hidden" name="foto_album" value="<?= $mod->foto_album; ?>"/>

        <figure class="mostrar-imagem">
            <img src="..<?= $mod->imagem; ?>" alt=""/>
        </figure>

        <p class="form-paragr">
	        <?= $this->aux_form->_campo_geral('texto', 'titulo', 'titulo', $mod->apelido, TXT_ROTULO_TITULO); ?>
        </p>

        <p class="form-paragr">
            <label for="txt-descr" class="form-rotulo"><?= TXT_ROTULO_DESCR; ?>:</label><br/>
            <textarea name="descr" id="txt-descr" class="form-controle form-controle-textarea"><?= $mod->descr; ?></textarea>
        </p>

        <p class="form-paragr">
            <?= $this->aux_form->_chk_sim_nao('capa', 'capa', TXT_ROTULO_CAPA, MSG_DICA_ALBUMFOTO_CAPA, $mod->capa ? ' CHECKED' : ''); ?>
        </p>

        <p class="form-paragr">
            <?= $this->aux_form->_chk_sim_nao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]