<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) )
    $params = $this->_obterparams();

$mod = $params['modelo'];

?>

<section class="dl3">
    <h1><?= $params['titulo']; ?></h1>

    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset>
            <legend><?= TXT_LEGENDA_HISTORIA; ?></legend>

            <p class="form-p-campo">
                <textarea name="historia"><?= $mod->historia; ?></textarea>
            </p>
        </fieldset>

        <fieldset>
            <legend><?= TXT_LEGENDA_MISSAO; ?></legend>

            <p class="form-p-campo">
                <textarea name="missao"><?= $mod->missao; ?></textarea>
            </p>
        </fieldset>

        <fieldset>
            <legend><?= TXT_LEGENDA_VISAO; ?></legend>

            <p class="form-p-campo">
                <textarea name="visao"><?= $mod->visao; ?></textarea>
            </p>
        </fieldset>

        <fieldset>
            <legend><?= TXT_LEGENDA_VALORES; ?></legend>

            <p class="form-p-campo">
                <textarea name="valores"><?= $mod->valores; ?></textarea>
            </p>
        </fieldset>

        <p class="form-p-campo">
            <label><?= TXT_LABEL_PUBLICAR; ?></label><br/>
            <input type="checkbox" name="publicar" id="chk-publicar" class="s-ou-n" value="1"<?= $mod->publicar || $params['incluindo'] ? ' CHECKED' : ''; ?>/>
            <label for="chk-publicar"></label>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
</section>