<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>" enctype="multipart/form-data">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_TIPO_DADO; ?></legend>

            <p class="form-paragr">
                <?php echo $this->aux_form->_campo_geral('texto', 'descr', 'descr', $mod->descr, TXT_ROTULO_DESCR, null, ['required' => 'required']); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->_arquivo_upload('icone', 'icone', TXT_ROTULO_ICONE, [], implode(', ', $mod->conf_extensoes_icone)); ?>

                <?php if( $mod->icone != '' ): ?>
                <figure class="mostrar-icone">
                    <img src="..<?php echo $mod->icone; ?>" alt=""/>
                </figure>
                <?php endif; ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->_chk_sim_nao('rede_social', 'rede-social', TXT_ROTULO_REDE_SOCIAL, null, $mod->rede_social ? ' CHECKED' : ''); ?>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_OPCOES_AVANCADAS; ?></legend>

            <p class="form-paragr">
	            <?php echo $this->aux_form->_campo_geral('texto', 'mascara', 'mascara', $mod->mascara, TXT_ROTULO_MASCARA, TXT_DICA_TIPODADO_MASCARA); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->_campo_geral('texto', 'expreg', 'expreg', $mod->expreg, TXT_ROTULO_EXPREG, TXT_DICA_TIPODADO_EXPREG); ?>
            </p>
        </fieldset>

        <p class="form-paragr">
	        <?php echo $this->aux_form->_chk_sim_nao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
        </p>

        <p class="form-botoes">
            <?php
            echo $this->aux_form->_botao('salvar', TXT_BOTAO_SALVAR);
            echo $this->aux_form->_botao('cancelar', TXT_BOTAO_CANCELAR);
            ?>
        </p>
    </form>
[/DL3-CONTEUDO]
