<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 16:51:21
 */

if( !isset($params) )
    $params = $this->_obterparams();

?>

<section class="dl3">
    <h1><?= $params['titulo']; ?></h1>

    <?php if( $params['perm-inserir?'] ): ?>
    <!-- Inserir um novo registro -->
    <a href="website/assuntos-contato/novo" class="com-icone a-inserir"><?= TXT_LINK_NOVO_ASSUNTO; ?></a>
    <?php endif; ?>

    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/form_filtro.phtml'; ?>

    <form id="form-editar-lista" method="post" action="website/assuntos-contato/remover-assunto">
        <!-- Exibir a lista com os registros selecionados -->
        <table class="lista">
            <thead>
                <tr>
                    <th id="th-id" class="td-id"><input type="checkbox"/></th>
                    <th id="th-descr"><?= TXT_TABELA_TITULO_DESCR; ?></th>
                    <th id="th-email" class="v-desk"><?= TXT_TABELA_TITULO_EMAIL; ?></th>
                    <th id="th-publicado"><?= TXT_TABELA_TITULO_PUBLICADO; ?></th>
                    <th id="th-opcoes" class="td-opcoes"><?= TXT_TABELA_TITULO_OPCOES; ?></th>
                </tr>
            </thead>

            <tbody>
                <?php if( !count($params['lista']) )
                    echo '<tr class="sem-registros"><td colspan="5">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO,'</td></tr>';

                foreach( $params['lista'] as $l ): ?>
                <tr>
                    <td headers="th-id" class="td-id"><input type="checkbox" name="id[]" value="<?= $l['assunto_contato_id']; ?>"/></td>
                    <td headers="th-descr">
                        <span class="mostrar-cor" style="background-color: <?= $l['assunto_contato_cor']; ?>; width: 10px; height: 10px; display: inline-block;"></span>
                        <?= $l['assunto_contato_descr']; ?>
                    </td>
                    <td headers="th-email" class="v-desk"><?= $l['assunto_contato_email']; ?></td>
                    <td headers="th-publicado"><?= $l['PUBLICADO']; ?></td>
                    <td headers="th-opcoes" class="td-opcoes">
                        <?php if( $params['perm-editar?'] ): ?>
                        <a href="website/assuntos-contato/editar/<?= $l['assunto_contato_id']; ?>" class="com-icone a-editar" title="<?= TXT_LINK_TITLE_EDITAR; ?>">
                            <?= TXT_LINK_EDITAR; ?>
                        </a>
                        <?php endif;

                        if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="SelecionarLinha(this); $el.submit();" class="com-icone a-remover" title="<?= TXT_LINK_TITLE_REMOVER; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

            <tfoot>
                <?php if( count($params['lista']) ): ?>
                <tr class="com-marcados">
                    <td colspan="5">
                        <?php if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="$el.submit();" class="com-icone a-remover" title="<?= TXT_LINK_TITLE_REMOVER_SELECIONADOS; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endif; ?>
            </tfoot>
        </table>
    </form>

    <div id="paginacao"></div>
</section>