<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 16:51:21
 */

if( !isset($params) )
    $params = $this->_obterparams();

?>

[DL3-CONTEUDO]
    <?php if( $params['perm-inserir?'] ): ?>
    <!-- Inserir um novo registro -->
    <a href="website/albuns-de-fotos/novo" class="com-icone ico-inserir"><?= TXT_LINK_NOVO_ALBUM; ?></a>
    <?php endif;

    include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/form_filtro.phtml'; ?>

    <form id="form-editar-lista" method="post" action="website/albuns-de-fotos/excluir-albuns">
        <!-- Exibir a lista com os registros selecionados -->
        <table class="lista-registros">
            <thead class="tbl-titulos">
                <tr class="tbl-linha">
                    <th id="th-chk" class="tbl-celula-chk"><input type="checkbox"/></th>
                    <?php if( $params['exibir-id'] ): ?>
                    <th id="th-id" class="tbl-celula-id"><?= TXT_LISTA_TITULO_ID; ?></th>
                    <?php endif; ?>
                    <th id="th-nome"><?= TXT_LISTA_TITULO_NOME; ?></th>
                    <th id="th-publicado"><?= TXT_LISTA_TITULO_PUBLICADO; ?></th>
                    <th id="th-opcoes" class="tbl-celula-opcoes"><?= TXT_LISTA_TITULO_OPCOES; ?></th>
                </tr>
            </thead>

            <tbody class="tbl-conteudo">
                <?php if( !count($params['lista']) )
                    echo '<tr class="tbl-linha sem-registros"><td>', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO,'</td></tr>';

                foreach( $params['lista'] as $l ): ?>
                <tr class="tbl-linha">
                    <td headers="th-chk" class="tbl-celula-chk"><input type="checkbox" name="id[]" value="<?= $l['album_id']; ?>"/></td>
                    <?php if( $params['exibir-id'] ): ?>
                    <td headers="th-id" class="tbl-celula-id"><?= $l['album_id']; ?></td>
                    <?php endif; ?>
                    <td headers="th-nome" class="tbl-celula-infos">
                        <?php if( !empty($l['foto_album_imagem']) ): ?>
                        <img src="..<?= $l['foto_album_imagem']; ?>" alt="" class="tbl-imagem capa-album v-desk"/>
                        <?php endif;

                        echo $l['album_nome'], '<br/>'; ?>
                    </th>
                    <td headers="th-publicado"><?= $l['PUBLICADO']; ?></th>
                    <td headers="th-opcoes" class="tbl-celula-opcoes">
                        <?php if( $params['perm-editar?'] ): ?>
                        <a href="javascript:;" onclick="SelecionarLinha(this); AlternarPublicacao('website/albuns-de-fotos/alternar-publicacao/<?= ($p = $l['PUBLICADO'] == 'Sim') ? 'ocultar' : 'publicar'; ?>');" class="so-icone ico-<?= $p ? 'nao-' : ''; ?>publicar" title="<?= $p ? TXT_LINK_TITLE_OCULTAR : TXT_LINK_TITLE_PUBLICAR; ?>">
                            <?= $p ? TXT_LINK_OCULTAR : TXT_LINK_PUBLICAR; ?>
                        </a>

                        <a href="website/albuns-de-fotos/editar/<?= $l['album_id']; ?>" class="so-icone ico-editar" title="<?= TXT_LINK_TITLE_EDITAR; ?>">
                            <?= TXT_LINK_EDITAR; ?>
                        </a>
                        <?php endif;

                        if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="SelecionarLinha(this); $el.submit();" class="so-icone ico-remover" title="<?= TXT_LINK_TITLE_REMOVER; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

            <tfoot class="tbl-rodape">
                <?php if( count($params['lista']) ): ?>
                <tr class="tbl-linha com-marcados">
                    <td>
                        <?php if( $params['perm-editar?'] ): ?>
                        <a href="javascript:;" onclick="SelecionarLinha(this); AlternarPublicacao('website/albuns-de-fotos/alternar-publicacao/publicar');" class="so-icone ico-publicar" title="<?= TXT_LINK_TITLE_PUBLICAR_SELECIONADOS; ?>">
                            <?= TXT_LINK_PUBLICAR; ?>
                        </a>

                        <a href="javascript:;" onclick="SelecionarLinha(this); AlternarPublicacao('website/albuns-de-fotos/alternar-publicacao/ocultar');" class="so-icone ico-nao-publicar" title="<?= TXT_LINK_TITLE_OCULTAR_SELECIONADOS; ?>">
                            <?= TXT_LINK_OCULTAR; ?>
                        </a>
                        <?php endif;

                        if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="$el.submit();" class="so-icone ico-remover" title="<?= TXT_LINK_TITLE_REMOVER_SELECIONADOS; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endif; ?>
            </tfoot>
        </table>
    </form>

    <div id="paginacao"></div>
[/DL3-CONTEUDO]