<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 16:51:21
 */

!isset($params) and $params = $this->_obterparams();

$campos = \Funcoes::_remover_coluna($params['lista'], 'ID');

?>

[DL3-CONTEUDO]
    <nav class="dl3-links">
	    <!-- Inserir um novo registro -->
		<?php if( $params['opcoes']['inserir?'] )
			echo $this->aux_links->_link('inserir', "{$params['dir-lista']}novo", $params['link-inserir']); ?>
    </nav>

    <form id="form-editar-lista" method="post" action="<?php echo $params['form-acao']; ?>">
        <!-- Exibir a lista com os registros selecionados -->
        <table class="lista-registros">
            <thead class="tbl-titulos">
                <tr class="tbl-linha">
                    <th id="th-chk" class="tbl-celula-chk"><input type="checkbox"/></th>
                    <?php
                    if( $params['exibir-id?'] )
                        echo $this->aux_lista->_celula_titulo('th-id', TXT_LISTA_TITULO_ID, ['class' => 'tbl-celula-id']);

                    foreach( $campos[0] as $tt => $lt )
						echo $this->aux_lista->_celula_titulo($this->aux_lista->_th_id($tt), $tt);

                    echo $this->aux_lista->_celula_titulo('th-opcoes', TXT_LISTA_TITULO_OPCOES, ['class' => 'tbl-celula-opcoes']);
                    ?>
                </tr>
            </thead>

            <tbody class="tbl-conteudo">
                <?php if( !count($params['lista']) )
                    echo '<tr class="tbl-linha sem-registros"><td>', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO,'</td></tr>';

                foreach( $params['lista'] as $k => $l ): ?>
                <tr class="tbl-linha">
                    <td headers="th-chk" class="tbl-celula-chk"><input type="checkbox" name="id[]" value="<?php echo $l['ID']; ?>"/></td>
                    <?php if( $params['exibir-id?'] )
                        echo $this->aux_lista->_celula_comum('th-id', $l['ID'], ['class' => 'tbl-celula-id']);

                    foreach( $campos[$k] as $k2 => $c ){
                        echo $this->aux_lista->_celula_comum(
                            $this->aux_lista->_th_id($k2),
	                        $k2 === TXT_LISTA_TITULO_DATA ? \Funcoes::_formatardatahora($c, $_SESSION['formato_data_completo']) : $c,
                            ['class' => preg_match('~<br\/?>~', $c) ? 'tbl-celula-infos' : null]
                        );
                    } // Fim foreach ?>

                    <td headers="th-opcoes" class="tbl-celula-opcoes">
	                    <?php
	                    # Ver os detalhes desse registro
	                    if( $params['perm-detalhes?'] )
		                    echo $this->aux_links->_link('detalhes', "{$params['dir-lista']}mostrar-detalhes/{$l['ID']}", TXT_LINK_DETALHES, TXT_LINK_TITLE_DETALHES, false);

                        # Remover esse registro
                        if( $params['opcoes']['remover?'] )
                            echo $this->aux_links->_link('remover', 'javascript:', TXT_LINK_REMOVER, TXT_LINK_TITLE_REMOVER, false); ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

            <tfoot class="tbl-rodape">
                <?php if( count($params['lista']) ): ?>
                <tr class="tbl-linha com-marcados">
                    <td>
	                    <?php
	                    # Remover registros
	                    if( $params['opcoes']['remover?'] )
		                    echo $this->aux_links->_link('remover', 'javascript:', TXT_LINK_REMOVER, TXT_LINK_TITLE_REMOVER_SELECIONADOS, false); ?>
                    </td>
                </tr>
                <?php endif; ?>
            </tfoot>
        </table>
    </form>

    <div id="paginacao"></div>
[/DL3-CONTEUDO]