<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 16:51:21
 */

if( !isset($params) )
    $params = $this->_obterparams();

?>

<section class="dl3">
    <h1><?= $params['titulo']; ?></h1>

    <?php if( $params['perm-inserir?'] ): ?>
    <!-- Inserir um novo registro -->
    <a href="website/google-analytics/novo" class="com-icone a-inserir"><?= TXT_LINK_NOVO_GA; ?></a>
    <?php endif; ?>

    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/form_filtro.phtml'; ?>

    <form id="form-editar-lista" method="post" action="website/google-analytics/excluir-configuracao">
        <!-- Exibir a lista com os registros selecionados -->
        <table class="lista">
            <thead>
                <tr>
                    <th id="th-id" class="td-id"><input type="checkbox"/></th>
                    <th id="th-usuario"><?= TXT_TABELA_TITULO_USUARIO; ?></th>
                    <th id="th-perfil"><?= TXT_TABELA_TITULO_PERFIL; ?></th>
                    <th id="th-ativo"><?= TXT_TABELA_TITULO_ATIVO; ?></th>
                    <th id="th-opcoes" class="td-opcoes"><?= TXT_TABELA_TITULO_OPCOES; ?></th>
                </tr>
            </thead>

            <tbody>
                <?php if( !count($params['lista']) )
                    echo '<tr class="sem-registros"><td colspan="5">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO,'</td></tr>';

                foreach( $params['lista'] as $l ): ?>
                <tr>
                    <td headers="th-id" class="td-id"><input type="checkbox" name="id[]" value="<?= $l['ga_id']; ?>"/></td>
                    <td headers="th-usuario"><?= $l['ga_usuario']; ?></td>
                    <td headers="th-perfil"><?= $l['ga_perfil_id']; ?></td>
                    <td headers="th-ativo"><?= $l['ATIVO']; ?></td>
                    <td headers="th-opcoes" class="td-opcoes">
                        <?php if( $params['perm-editar?'] ): ?>
                        <a href="website/google-analytics/editar/<?= $l['ga_id']; ?>" class="com-icone a-editar" title="<?= TXT_LINK_TITLE_EDITAR; ?>">
                            <?= TXT_LINK_EDITAR; ?>
                        </a>
                        <?php endif;

                        if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="SelecionarLinha(this); $el.submit();" class="com-icone a-remover" title="<?= TXT_LINK_TITLE_REMOVER; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

            <tfoot>
                <?php if( count($params['lista']) ): ?>
                <tr class="com-marcados">
                    <td colspan="5">
                        <?php if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="$el.submit();" class="com-icone a-remover" title="<?= TXT_LINK_TITLE_REMOVER_SELECIONADOS; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endif; ?>
            </tfoot>
        </table>
    </form>

    <div id="paginacao"></div>
</section>