<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 14/01/2015 10:13:48
 */

?>

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $sf = $('#form-<?= $params['form-id']; ?>')._formulario({
        depois: function(){
            window.location = '<?= $params['url-depois']; ?>';
        },
        aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: null }
    });
    //]]>
</script>
[/DL3-SCRIPTS]