<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 05/01/2015 16:57:41
 */

# Parâmetros passados para a página
$params = $this->_obterparams();

?>

<!DOCTYPE html>
<html>
<head>
    <title><?= "{$params['titulo']} || ". \DL3::$ap_titulo; ?></title>
    <meta charset="<?= \DL3::$ap_charset; ?>">

    <!-- Setar a base do HTML -->
    <base href="<?= \DL3::$ap_base_html; ?>"/>

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?= \DL3::$dir_imgs . \DL3::$ap_favicon; ?>"/>

    <!-- Tamanho do dispositivo -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Aplicar o tema da página -->
    <?= \DL3::_carregartema($params['conf-site']['tema_diretorio']); ?>
</head>
<body>
    <div id="dl3-grid">
        <header class="dl3-topo">
            <a href="" class="logotipo"><?= \DL3::$ap_titulo; ?></a>
        </header>

        <nav class="dl3-menu">
            <ul class="menu-principal">
                <li class="menu-item">
                    <a href="" class="menu-texto ico-home">
                        <?= TXT_LINK_HOME; ?>
                    </a>
                </li>

                <li class="menu-item">
                    <a href="sobre" class="menu-texto ico-sobre">
                        <?= TXT_LINK_SOBRE; ?>
                    </a>
                </li>

                <li class="menu-item">
                    <a href="albuns-de-fotos" class="menu-texto ico-fotos">
                        <?= TXT_LINK_ALBUNS_FOTOS; ?>
                    </a>
                </li>

                <li class="menu-item">
                    <a href="contato" class="menu-texto ico-contato">
                        <?= TXT_LINK_CONTATO; ?>
                    </a>
                </li>
            </ul>
        </nav>

