<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 05/01/2015 16:57:41
 */

# Parâmetros passados para a página
$params = $this->_obterparams();

?>

<!DOCTYPE html>
<html>
<head>
    <title><?= "{$params['titulo']} || ". \DL3::$ap_titulo; ?></title>
    <meta charset="<?= \DL3::$ap_charset; ?>">

    <!-- Setar a base do HTML -->
    <base href="<?= \DL3::$ap_base_html; ?>"/>

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?= \DL3::$dir_imgs . \DL3::$ap_favicon; ?>"/>

    <!-- Tamanho do dispositivo -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Aplicar o tema da página -->
    <link rel="stylesheet" media="all" href="<?= \DL3::$dir_temas; ?>website/css/padrao.css"/>
    <link rel="stylesheet" media="all" href="<?= \DL3::$dir_temas; ?>website/css/links.css"/>
    <link rel="stylesheet" media="all" href="<?= \DL3::$dir_temas; ?>website/css/topo.css"/>
    <link rel="stylesheet" media="all" href="<?= \DL3::$dir_temas; ?>website/css/menu.css"/>
    <link rel="stylesheet" media="all" href="<?= \DL3::$dir_temas; ?>website/css/conteudo.css"/>
    <link rel="stylesheet" media="all" href="<?= \DL3::$dir_temas; ?>website/css/listas.css"/>
    <link rel="stylesheet" media="all" href="<?= \DL3::$dir_temas; ?>website/css/formularios.css"/>
    <link rel="stylesheet" media="all" href="<?= \DL3::$dir_temas; ?>website/css/rodape.css"/>
    <link rel="stylesheet" media="all" href="<?= \DL3::$dir_temas; ?>website/css/website.css"/>
</head>
<body>
    <div id="grid-layout">
        <header class="dl3">
            <a href="" class="logotipo"><?= \DL3::$ap_titulo; ?></a>
        </header>

        <nav class="dl3">
            <ul class="menu-principal sem-marcadores">
                <li class="menu-item">
                    <a href="" class="a-home">
                        <?= TXT_LINK_HOME; ?>
                    </a>
                </li>

                <li class="menu-item">
                    <a href="sobre" class="a-sobre">
                        <?= TXT_LINK_SOBRE; ?>
                    </a>
                </li>

                <li class="menu-item">
                    <a href="contato" class="a-contato">
                        <?= TXT_LINK_CONTATO; ?>
                    </a>
                </li>
            </ul>
        </nav>

