<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 05/01/2015 15:34:08
 */

?>

<section class="dl3-conteudo">
    <h1><?= \DL3::$ap_titulo; ?></h1>

    <div class="widgets flexivel">
        <div class="widget hm-usuario col-2">
            <h2 class="wg-titulo"><?= TXT_WIDGET_TITULO_MINHA_CONTA; ?></h2>

            <p class="wg-conteudo">
                <?= TXT_ROTULO_NOME .": {$_SESSION['usuario_info_nome']}"; ?><br/>
                <?= TXT_ROTULO_EMAIL .": {$_SESSION['usuario_info_email']}"; ?><br/>
                <?= TXT_ROTULO_LOGIN .": {$_SESSION['usuario_info_login']}"; ?><br/>
                <?= TXT_ROTULO_GRUPO .": {$_SESSION['grupo_usuario_descr']}"; ?><br/>
                <?= TXT_ROTULO_ULTIMO_LOGIN .': '. \Funcoes::_formatardatahora($_SESSION['usuario_ultimo_login'], $_SESSION['formato_data_completo']); ?><br/>
            </p>

            <p class="wg-conteudo">
                <a href="admin/usuarios/minha-conta" class="wg-link com-icone a-detalhes">
                    <?= TXT_LINK_EDITAR_DADOS; ?>
                </a>
            </p>
        </div>

        <div class="widget hm-contatos col-2">
            <h2 class="wg-titulo"><?= TXT_RELATORIO_TITULO_CONTATOS; ?></h2>
            <?= $params['rel-contatos']; ?>

            <p class="wg-conteudo">
                <a href="website/contatos-recebidos" class="wg-link com-icone a-detalhes">
                    <?= TXT_LINK_TODOS_CONTATOS; ?>
                </a>
            </p>
        </div>

        <div class="widget hm-analytics col-2">
            <h2 class="wg-titulo"><?= TXT_RELATORIO_TITULO_ACESSOS_MENSAIS; ?></h2>

            <ul id="ga" class="wg-conteudo sem-marcadores">
                <li class="ga-valor atras-2">
                    <h3><?= MSG_MES; ?></h3>
                    <div class="visitas"></div>
                </li>

                <li class="ga-valor atras-1">
                    <h3><?= MSG_MES; ?></h3>
                    <div class="visitas"></div>
                </li>

                <li class="ga-valor atual">
                    <h3><?= MSG_MES; ?></h3>
                    <div class="visitas"></div>
                </li>
            </ul>

            <p class="wg-conteudo">
                <a href="website/google-analytics" class="wg-link com-icone a-detalhes">
                    <?= TXT_LINK_CONFIGURACOES_GOOGLE_ANALYTICS; ?>
                </a>
            </p>
        </div>
    </div>
</section>

<script>
    //<![CDATA[
    window.addEventListener('load', function(){
        // Acessos mensais
        // Mês atual
        GoogleAnalytics('<?= date('Y-m-01'); ?>', '<?= date('Y-m-t'); ?>', 'month', null, $('#ga > .atual'));

        // Mês passado
        GoogleAnalytics('<?= date('Y-m-01', strtotime('-1 month')); ?>', '<?= date('Y-m-t', strtotime('-1 month')); ?>', 'month', null, $('#ga > .atras-1'));

        // 2 meses atrás
        GoogleAnalytics('<?= date('Y-m-01', strtotime('-2 month')); ?>', '<?= date('Y-m-t', strtotime('-2 month')); ?>', 'month', null, $('#ga > .atras-2'));
    });

    function GoogleAnalytics(dt_inicio, dt_fim, dimensao, metricas, $objeto){
        $.ajax({
            url     : 'home/google-analytics/acessos/'+ dt_inicio +'/'+ dt_fim +'/'+ dimensao,
            dataType: 'json',
            success : function(json){
                $objeto.find('h3').html($objeto.find('h3').html() +' '+ json[0].dimensao);
                $objeto.find('.visitas').html(json[0].visitas);
            },
            beforeSend: function(){
                $(document.createElement('img')).css({
                    /* Tamanho */
                    width: 'auto',
                    height: '20px'
                }).attr({ src: '../<?= \DL3::$dir_temas . 'painel-dl/css/imagens/loading-min.gif'; ?>' }).appendTo($objeto.find('> .visitas'));
            }
        });
    }
    //]]>
</script>