<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 05/01/2015 16:57:41
 */

# Parâmetros passados para a página
$params = $this->_obterparams();

?>

<!DOCTYPE html>
<html>
<head>
    <title><?= "{$params['titulo']} || ". \DL3::$ap_titulo; ?></title>
    <meta charset="<?= \DL3::$ap_charset; ?>">

    <!-- Setar a base do HTML -->
    <base href="<?= \DL3::$ap_base_html; ?>"/>

    <!-- Tamanho do dispositivo -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link rel="shortcut icon" href="../<?= \DL3::$dir_imgs . \DL3::$ap_favicon; ?>"/>
    
    <!-- Aplicar o tema da página -->
    <link rel="stylesheet" media="all" href="../<?= \DL3::$dir_temas; ?>painel-dl/css/padrao.css"/>
    <link rel="stylesheet" media="all" href="../<?= \DL3::$dir_temas; ?>painel-dl/css/links.css"/>
    <link rel="stylesheet" media="all" href="../<?= \DL3::$dir_temas; ?>painel-dl/css/topo.css"/>
    <link rel="stylesheet" media="all" href="../<?= \DL3::$dir_temas; ?>painel-dl/css/formularios.css"/>
    <link rel="stylesheet" media="all" href="../<?= \DL3::$dir_temas; ?>painel-dl/css/rodape.css"/>
    <link rel="stylesheet" media="all" href="../<?= \DL3::$dir_temas; ?>painel-dl/css/login.css"/>
</head>
<body>
    <div id="grid-layout">
        <header class="dl3-topo">
            <a href="" class="logotipo"><?= \DL3::$ap_titulo; ?></a>
        </header>

