<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 23:32:01
 */

!isset($params) and $params = $this->_obterparams();

?>

<form id="form-filtro" method="get" class="form-filtro">
	<?= $this->aux_form->_campo_geral('busca', 't', 't', $params['get-t'], null, null, [
		'placeholder' => TXT_DICA_FORM_FILTRO, 'required' => 'required']
	); ?>
    <?php
    $qc = count($params['campos']);

    if( $qc === 1 ): ?>
    <input type="hidden" name="c" value="<?= $params['campos'][0]['valor']; ?>"/>
    <input type="hidden" name="o" value="<?= $params['campos'][0]['valor']; ?>"/>
    <?php elseif( $qc > 1 ):
        echo $this->aux_form->_combo_select('c', 'c', $params['get-c'], null, null, [], $params['campos']);
		echo $this->aux_form->_combo_select('o', 'o', $params['get-o'], null, null, [], $params['campos']);
    endif; ?>

    <?php if( $params['filtro?'] ): ?>
    <a href="javascript:" onclick="self.location = '<?= filter_input(INPUT_SERVER, 'REDIRECT_URL'); ?>';" class="a-limpar-filtro">
        <?= TXT_LINK_LIMPAR_FILTRO; ?>
    </a>
    <?php endif; ?>

    <button type="submit" class="btn-filtrar"><?= TXT_BOTAO_FILTRAR; ?></button>
</form>