<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 14/01/2015 10:13:48
 */

!isset($params) and $params = $this->_obterparams();

?>

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $sf = $('#form-<?= $params['form-id']; ?>')._formulario({
        depois: function(){
	        var url = '<?= $params['url-depois']; ?>';

	        if( !/^\//.test(url) ) url = $('base').attr('href') + url;

	        window.location = url;
        },
        aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: null }
    }).on('reset', function(){ history.back(); });
    //]]>
</script>
[/DL3-SCRIPTS]