<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 14/01/2015 10:44:51
 */

!isset($params) and $params = $this->_obterparams();

?>

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $el = $('#form-editar-lista')._formulario({
        cktodos : [true, 'thead :checkbox', 'tbody :checkbox'],
        depois  : function(){
            // Remover o item da lista
            $el.find('tbody :checked').parents('tr').remove();
        },
        aparencia: { tema: '<?php echo DL3::$plugin_formulario_tema; ?>', estilo: null }
    });

    $pg = $('#paginacao')._paginacao({
        pgtotal : <?php echo $params['total-pg']; ?>,
        mostrar : 5,
        tema    : '<?php echo \DL3::$plugin_paginacao_tema; ?>'
    });

    $('.com-marcados > *:first-child,.sem-registros > *:first-child').attr({ 'colspan': $('.tbl-titulos > .tbl-linha:first-child > *').length });
    //]]>
</script>
[/DL3-SCRIPTS]