<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 05/01/2015 17:06:01
 */

?>

        <footer class="dl3">
            <?= \DL3::$ap_titulo .' &copy; '. date('Y'); ?>
        </footer>
    </div>

    <!-- Formulário para fazer logout -->
    <form id="form-logout" method="post" action="login/fazer-logout"></form>

    <!-- Javascripts -->
    <script src="../<?= \DL3::$dir_js; ?>jquery-<?= \DL3::$ap_versao_jquery; ?>-min.js"></script>
    <script src="../<?= \DL3::$dir_js; ?>dl-formulario/dl-formulario-2.0.plugin.js"></script>
    <script src="../<?= \DL3::$dir_js; ?>dl-paginacao/dl-paginacao-2.0.plugin.js"></script>
    <script src="../<?= \DL3::$dir_js; ?>dl-framework.js"></script>

    <script>
        //<![CDATA[
        $logout = $('#form-logout')._dlformulario({
            depois: function(){
                window.location.reload();
            },
            aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: null }
        });
        //]]>
    </script>
</body>
</html>