<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 05/01/2015 17:06:01
 */

?>

        <footer class="dl3-rodape">
            <?= \DL3::$ap_titulo .' v'. \DL3::$ap_versao .' &copy; '. date('Y'); ?>
        </footer>
    </div>

    <!-- Formulário para fazer logout -->
    <form id="form-logout" method="post" action="login/fazer-logout"></form>

    <!-- Javascripts -->
    <script src="../<?= \DL3::$dir_js; ?>jquery-<?= \DL3::$ap_versao_jquery; ?>-min.js"></script>
    <script src="../<?= \DL3::$dir_js; ?>dl-formulario/dl-formulario-2.0.plugin.js"></script>
    <script src="../<?= \DL3::$dir_js; ?>dl-paginacao/dl-paginacao-2.0.plugin.js"></script>
    <script src="../<?= \DL3::$dir_js; ?>dl-framework.js"></script>

    <script>
        //<![CDATA[
        $logout = $('#form-logout')._dlformulario({
            depois: function(){
                window.location.reload();
            },
            aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: null }
        });

        <?php if( $params['mostrar-filtro-menu?'] ): ?>
        $('#form-filtro-modulos #txt-bm').on('input', function(){
            var $th = $(this);
            var $mf = $('#menu-filtro');
            var vlr = $th.val();

            if( vlr !== (false || '') )
                $mf.slideDown('fast');
            else
                $mf.slideUp('fast');

            $mf.find('> *, .menu-item, .sm-item').css({ display: 'none' });
            $mf.find('.sm-item:contains('+ vlr +')').css({ display: 'block' }).parents('.menu-item').css({ display: 'block' });
        }).on('blur', function(){
            var $mf = $('#menu-filtro');
            $mf.slideUp('slow');
        });
        <?php endif; ?>
        //]]>
    </script>
</body>
</html>