<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 08/01/2015 16:24:44
 */

!isset($params) and $params = $this->_obterparams();

?>

[DL3-CONTEUDO]
	<?php if( !$params['incluindo'] ): ?>
	<p class="log-registro">
	    <?php !empty($params['dt-inc'])
			and printf(TXT_DIVERSOS_REGISTRO_CRIADO .'<br/>', $params['u-inc'], $params['dt-inc']);

	    !empty($params['dt-alt'])
	        and printf(TXT_DIVERSOS_REGISTRO_ATUALIZADO, $params['u-alt'], $params['dt-alt']); ?>
	</p>
	<?php endif; ?>
[/DL3-CONTEUDO]
