<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 05/01/2015 17:31:20
 */

!isset($params) and $params = $this->_obterparams();

?>

[DL3-CONTEUDO]
    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <p class="form-paragr">
            <label for="txt-nome" class="form-rotulo"><?= TXT_ROTULO_NOME; ?>:</label><br/>
            <input type="text" name="nome" id="txt-nome" class="form-controle" required/>
        </p>

        <p class="form-paragr">
            <label for="mail-email" class="form-rotulo"><?= TXT_ROTULO_EMAIL; ?>:</label><br/>
            <input type="email" name="email" id="mail-email" class="form-controle" required/>
        </p>

        <p class="form-paragr">
            <label for="tel-fone"><?= TXT_ROTULO_FONE; ?>:</label><br/>

            <span class="form-dica">
                <!-- Alternar a mácara do telefone -->
                <input type="checkbox" id="alt-mask-fone" data-telefone="#tel-fone"/>
                <label for="alt-mask-fone"><?= TXT_ROTULO_ALT_MASK_FONE; ?></label><br/>
            </span>

            <input type="tel" name="telefone" id="tel-fone" pattern="<?= \Funcoes::_expreg_form(EXPREG_TELEFONE_GERAL); ?>" class="form-controle"/>
        </p>

        <?php if( $params['mostrar-assunto?'] && count($params['assuntos']) > 0 ): ?>
        <p class="form-paragr">
            <label for="sel-assunto" class="form-rotulo"><?= TXT_ROTULO_ASSUNTO; ?>:</label><br/>
            <select name="assunto" id="sel-assunto" class="form-controle" required>
                <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>

                <?php foreach( $params['assuntos'] as $o ): ?>
                <option value="<?= $o['VALOR']; ?>"><?= $o['TEXTO']; ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        <?php endif; ?>

        <p class="form-paragr">
            <label for="ta-mensagem" class="form-rotulo"><?= TXT_ROTULO_MENSAGEM; ?>:</label><br/>
            <textarea name="mensagem" id="ta-mensagem" class="form-controle form-textarea" required></textarea>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-enviar"><?= TXT_BOTAO_ENVIAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    // Aplicar as máscaras
    $('#tel-fone')._mascara('<?= MASK_TELEFONE_CELULAR_8; ?>');

    $('#alt-mask-fone').on('change',
	    { msk8: '<?= MASK_TELEFONE_CELULAR_8; ?>', msk9: '<?= MASK_TELEFONE_CELULAR_9; ?>' },
	    AlternarMaskFone
    );
    //]]>
</script>
[/DL3-SCRIPTS]
