<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <h2 class="titulo-h2"><?= TXT_PAGINA_TITULO_MODULO; ?></h2>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_MODULO; ?></legend>

            <?php if( $params['modulos-pai'] != false ): ?>
            <p class="form-paragr">
	            <?= $this->aux_form->_combo_select('pai', 'pai', $mod->pai, TXT_ROTULO_MODULO_PAI, null, [],
		            array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], $params['modulos-pai'])
	            ); ?>
            </p>
            <?php endif; ?>

            <p class="form-paragr">
                <?= $this->aux_form->_campo_geral('texto', 'nome', 'nome', $mod->nome, TXT_ROTULO_NOME, null, ['required' => 'required']); ?>
            </p>

            <p class="form-paragr">
                <label for="txt-descr" class="form-rotulo"><?= TXT_ROTULO_DESCRICAO; ?>:</label><br/>
                <textarea name="descr" id="txt-descr" class="form-controle form-controle-textarea"><?= $mod->descr; ?></textarea>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_MENU; ?></legend>

            <p class="form-paragr">
	            <?= $this->aux_form->_chk_sim_nao('menu', 'menu', TXT_ROTULO_MENU, TXT_DICA_MODULO_MENU, $mod->menu ? ' CHECKED' : ''); ?>
            </p>

            <p class="form-paragr">
	            <?= $this->aux_form->_campo_geral('texto', 'link', 'link', $mod->link, TXT_ROTULO_LINK, null, ['required' => 'required']); ?>
            </p>

            <p class="form-paragr">
	            <?= $this->aux_form->_campo_geral('numero', 'ordem', 'ordem', $mod->ordem, TXT_ROTULO_ORDEM, null, [
		            'min' => -99, 'max' => 99, 'required' => 'required'
	            ]); ?>
            </p>
        </fieldset>

        <p class="form-paragr">
	        <?= $this->aux_form->_chk_sim_nao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $('#sel-pai').on('change', function(){
        var $forms = $('#form-funcs, #form-remover-func');

        $(this).val() !== '' ? $forms.show('fast') : $forms.hide('fast');
    });
    //]]>
</script>
[/DL3-SCRIPTS]
