<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) )
    $params = $this->_obterparams();

$mod = $params['modelo'];

?>

<section class="dl3">
    <h1><?= $params['titulo']; ?></h1>

    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <p class="form-p-campo">
            <label for="txt-descr"><?= TXT_LABEL_DESCRICAO; ?>:</label><br/>
            <input type="text" name="descr" id="txt-descr" value="<?= $mod->descr; ?>" required/>
        </p>

        <p class="form-p-campo">
            <label for="txt-diretorio"><?= TXT_LABEL_DIRETORIO; ?>:</label><br/>
            <input type="text" name="diretorio" id="txt-diretorio" value="<?= $mod->diretorio; ?>" required/>
        </p>

        <p class="form-p-campo">
            <label><?= TXT_LABEL_PADRAO; ?></label><br/>
            <input type="checkbox" name="padrao" id="chk-padrao" class="s-ou-n" value="1"<?= $mod->padrao ? ' CHECKED' : ''; ?>/>
            <label for="chk-padrao"></label>
        </p>

        <p class="form-p-campo">
            <label><?= TXT_LABEL_PUBLICAR; ?></label><br/>
            <input type="checkbox" name="publicar" id="chk-publicar" class="s-ou-n" value="1"<?= $mod->publicar || $params['incluindo'] ? ' CHECKED' : ''; ?>/>
            <label for="chk-publicar"></label>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
</section>