<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <h2 class="titulo-h2"><?= TXT_PAGINA_TITULO_MODULO; ?></h2>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_MODULO; ?></legend>

            <?php if( $params['modulos-pai'] != false ): ?>
            <p class="form-paragr">
	            <?= $this->aux_form->_combo_select('pai', 'pai', $mod->pai, TXT_ROTULO_MODULO_PAI, null, ['required' => 'required'],
		            array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], $params['modulos-pai'])
	            ); ?>
            </p>
            <?php endif; ?>

            <p class="form-paragr">
                <?= $this->aux_form->_campo_geral('texto', 'nome', 'nome', $mod->nome, TXT_ROTULO_NOME, null, ['required' => 'required']); ?>
            </p>

            <p class="form-paragr">
                <label for="txt-descr" class="form-rotulo"><?= TXT_ROTULO_DESCRICAO; ?>:</label><br/>
                <textarea name="descr" id="txt-descr" class="form-controle form-textarea"><?= $mod->descr; ?></textarea>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_MENU; ?></legend>

            <p class="form-paragr">
	            <?= $this->aux_form->_chk_sim_nao('menu', 'menu', TXT_ROTULO_MENU, TXT_DICA_MODULO_MENU, $mod->menu ? ' CHECKED' : ''); ?>
            </p>

            <p class="form-paragr">
	            <?= $this->aux_form->_campo_geral('texto', 'link', 'link', $mod->link, TXT_ROTULO_LINK, null, ['required' => 'required']); ?>
            </p>

            <p class="form-paragr">
	            <?= $this->aux_form->_campo_geral('numero', 'ordem', 'ordem', $mod->ordem, TXT_ROTULO_ORDEM, null, [
		            'min' => -99, 'max' => 99, 'required' => 'required'
	            ]); ?>
            </p>
        </fieldset>

        <p class="form-paragr">
	        <?= $this->aux_form->_chk_sim_nao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>

    <?php if( $params['mostrar-funcs?'] ): ?>
    <h2 class="titulo-h2"><?= TXT_PAGINA_TITULO_CONFIGURACOES_AVANCADAS; ?></h2>

    <form id="form-funcs" method="post" action="desenvolvedor/modulos/inserir-funcionalidade">
        <input type="hidden" name="func_modulo" value="<?= $mod->id; ?>"/>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_FUNCIONALIDADES; ?></legend>

            <p class="form-paragr">
	            <?= $this->aux_form->_campo_geral('texto', 'descr', 'descr', null, TXT_ROTULO_DESCRICAO, null, ['required' => 'required']); ?>
            </p>

            <p class="form-paragr">
	            <?= $this->aux_form->_campo_geral('texto', 'classe', 'classe', $params['modulo-classe'], TXT_ROTULO_CLASSE, null, ['required' => 'required']); ?>
            </p>

            <ul id="metodos" class="sub-itens">
                <li class="item">
	                <?= $this->aux_form->_campo_geral('texto', 'metodos[]', '', null, null, null, [
		                'placeholder' => TXT_ROTULO_METODO, 'required' => 'required'
	                ]); ?>
                <li>
            </ul>

            <a href="javascript:;" onclick="NovoMetodo();" class="com-icone ico-inserir">
                <?= TXT_LINK_NOVO_METODO; ?>
            </a>
        </fieldset>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>

    <form id="form-remover-func" method="post" action="desenvolvedor/modulos/apagar-funcionalidade">
        <table class="lista-registros">
            <thead class="tbl-titulos">
                <tr class="tbl-linha">
                    <th id="th-id" class="tbl-celula-id"><input type="checkbox"/></th>
                    <th id="th-descr"><?= TXT_LISTA_TITULO_DESCR; ?></th>

                    <th id="th-opcoes" class="tbl-celula-opcoes"><?= TXT_LISTA_TITULO_OPCOES; ?></th>
                </tr>
            </thead>

            <tbody class="tbl-conteudo">
                <?php if( !count($params['funcs']) )
                    echo '<tr class="tbl-linha sem-registros"><td colspan="3">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';

                foreach( $params['funcs'] as $l ): ?>
                <tr class="tbl-linha">
                    <td headers="th-id" class="tbl-celula-id">
                        <input type="checkbox" name="id[]" value="<?= $l['VALOR']; ?>"/>
                    </td>
                    <td headers="th-descr"><?= $l['TEXTO']; ?></td>
                    <td headers="th-opcoes" class="tbl-celula-opcoes">
                        <a href="javascript:;" onclick="SelecionarLinha(this); $rf.submit();" class="so-icone ico-remover">
                            <?= TXT_LINK_REMOVER;?>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </form>
    <?php endif; ?>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $('#form-funcs')._formulario({
        depois: function(){ window.location.reload(); },
        aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: null }
    });

    $rf = $('#form-remover-func')._formulario({
        depois: function(){
            $('table.lista :checked').parents('tr').remove();
        },
        aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: null }
    });

    $('#sel-pai').on('change', function(){
        var $forms = $('#form-funcs, #form-remover-func');

        $(this).val() !== '' ? $forms.show('fast') : $forms.hide('fast');
    });

    function NovoMetodo(){
	    var $mtd = $('#metodos');
	    var $itm = $mtd.find('.item:first-child').clone().appendTo($mtd);
            $itm.find('input').removeAttr('id').removeAttr('tabindex');

	    // Criar botão para remover
	    $(document.createElement('a')).html('x').attr('href', 'javascript:;').on('click', function(){
		   $(this).parents('.item').fadeOut('fast', function(){
			   $(this).remove();
		   });
	    }).appendTo($itm);
    } // Fim function NovoMetodo
    //]]>
</script>
[/DL3-SCRIPTS]
