<?php
/**
 * Created by PhpStorm.
 * User: dlepera
 * Date: 21/08/15
 * Time: 08:34
 */

!isset($params) and $params = $this->_obterparams();

?>

[DL3-CONTEUDO]
	<h2 class="titulo-h2"><?php echo TXT_PAGINA_TITULO_FUNCIONALIDADES; ?></h2>

	<nav class="dl3-links">
		<?php echo $this->aux_links->_link('inserir', 'javascript:', sprintf(TXT_LINK_NOVA, TXT_MODELO_MODULOFUNC), '', true, [
			'data-ajax' => true,
			'data-ajax-msg' => TXT_AJAX_CARREGANDO_CONTEUDO,
			'data-acao' => 'carregar-form',
			'data-acao-param-html' => "desenvolvedor/modulos/funcionalidades/novo/{$mod->id}"
		]); ?>
	</nav>

	<form id="form-remover-func" method="post" action="desenvolvedor/modulos/funcionalidades/excluir">
		<table class="lista-registros">
			<?php if( $params['qtde-registros'] > 0 ): ?>
				<caption class="tbl-subtitulo"><?php printf(TXT_LISTA_SUBTITULO_MOSTRANDO_X_REGISTROS, count($params['lista']), $params['qtde-registros']); ?></caption>
			<?php endif; ?>

			<thead class="tbl-titulos">
				<tr class="tbl-linha">
					<th id="th-chk" class="tbl-celula-id"><input type="checkbox"/></th>

					<th id="th-descr"><?php echo TXT_LISTA_TITULO_DESCR; ?></th>

					<th id="th-opcoes" class="tbl-celula-opcoes"><?php echo TXT_LISTA_TITULO_OPCOES; ?></th>
				</tr>
			</thead>

			<tbody class="tbl-conteudo">
			<?php if( !count($params['funcs']) )
				echo '<tr class="tbl-linha sem-registros"><td colspan="3">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';

			foreach( $params['funcs'] as $l ): ?>
				<tr class="tbl-linha">
					<td headers="th-chk" class="tbl-celula-id">
						<input type="checkbox" name="id[]" value="<?php echo $l['VALOR']; ?>"/>
					</td>
					<td headers="th-descr"><?php echo $l['TEXTO']; ?></td>

					<td headers="th-opcoes" class="tbl-celula-opcoes">
						<?php
						echo $this->aux_links->_link('editar', 'javascript:', TXT_LINK_EDITAR, TXT_LINK_TITLE_EDITAR, false, [
							'data-ajax' => true,
							'data-ajax-msg' => TXT_AJAX_CARREGANDO_CONTEUDO,
							'data-acao' => 'carregar-form',
							'data-acao-param-html' => "desenvolvedor/modulos/funcionalidades/editar/{$l['VALOR']}"
						]);
						echo $this->aux_links->_link('remover', 'javascript:', TXT_LINK_REMOVER, TXT_LINK_TITLE_REMOVER, false);
						?>
					</td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
	<script>
		$el = $('#form-remover-func')._formulario({
			depois: function(){
			$('.lista-registros :checked').parents('tr').remove();
			},
			aparencia: { tema: '<?php echo \DL3::$plugin_formulario_tema; ?>', estilo: null }
		});
	</script>
[/DL3-SCRIPTS]
