<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 16:51:21
 */

if( !isset($params) )
    $params = $this->_obterparams();
// echo '<pre>', var_dump($params), '</pre>';
?>

<section class="dl3">
    <h1><?= $params['titulo']; ?></h1>

    <?php if( $params['perm-inserir?'] ): ?>
    <!-- Inserir um novo registro -->
    <a href="desenvolvedor/modulos/novo" class="com-icone a-inserir"><?= TXT_LINK_NOVO_MODULO; ?></a>
    <?php endif; ?>

    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/form_filtro.phtml'; ?>

    <form id="form-editar-lista" method="post" action="desenvolvedor/modulos/desinstalar-modulo">
        <table class="lista">
            <thead>
                <tr>
                    <th id="th-id" class="td-id"><input type="checkbox"/></th>
                    <th id="th-idreg" class="v-desk"><?= TXT_TABELA_TITULO_ID; ?></th>
                    <th id="th-nome"><?= TXT_TABELA_TITULO_NOME; ?></th>
                    <th id="th-link" class="v-desk"><?= TXT_TABELA_TITULO_LINK; ?></th>
                    <th id="th-publicado"><?= TXT_TABELA_TITULO_PUBLICADO; ?></th>
                    <th id="th-opcoes" class="td-opcoes"><?= TXT_TABELA_TITULO_OPCOES; ?></th>
                </tr>
            </thead>

            <tbody>
                <?php if( !count($params['lista']) )
                    echo '<tr class="sem-registros"><td colspan="6">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';

                foreach( $params['lista'] as $l ): ?>
                <tr>
                    <td headers="th-id" class="td-id"><input type="checkbox" name="id[]" value="<?= $l['modulo_id']; ?>"/></td>
                    <td headers="th-idreg" class="v-desk"><?= $l['modulo_id']; ?></td>
                    <td headers="th-nome"><?= $l['NOME_COMPLETO']; ?></td>
                    <td headers="th-link" class="v-desk"><?= $l['modulo_link']; ?></td>
                    <td headers="th-publicado"><?= $l['PUBLICADO']; ?></td>
                    <td headers="th-opcoes" class="td-opcoes">
                        <?php if( $params['perm-editar?'] ): ?>
                        <a href="desenvolvedor/modulos/editar/<?= $l['modulo_id']; ?>" class="com-icone a-editar" title="<?= TXT_LINK_TITLE_EDITAR; ?>">
                            <?= TXT_LINK_EDITAR; ?>
                        </a>
                        <?php endif;

                        if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="SelecionarLinha(this); $el.submit();" class="com-icone a-remover" title="<?= TXT_LINK_TITLE_REMOVER; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

            <tfoot>
                <?php if( count($params['lista']) ): ?>
                <tr class="com-marcados">
                    <td colspan="6">
                        <?php if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="$el.submit();" class="com-icone a-remover" title="<?= TXT_LINK_TITLE_REMOVER_SELECIONADOS; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endif; ?>
            </tfoot>
        </table>
    </form>

    <div id="paginacao"></div>
</section>