<?php
/**
 * Created by PhpStorm.
 * User: dlepera
 * Date: 21/08/15
 * Time: 08:34
 */

!isset($params) and $params = $this->_obterparams();

?>

[DL3-CONTEUDO]
	<form id="form-remover-func" method="post" action="desenvolvedor/modulos/apagar-funcionalidade">
		<table class="lista-registros">
			<thead class="tbl-titulos">
			<tr class="tbl-linha">
				<th id="th-id" class="tbl-celula-id"><input type="checkbox"/></th>

				<th id="th-descr"><?= TXT_LISTA_TITULO_DESCR; ?></th>

				<th id="th-opcoes" class="tbl-celula-opcoes"><?= TXT_LISTA_TITULO_OPCOES; ?></th>
			</tr>
			</thead>

			<tbody class="tbl-conteudo">
			<?php if( !count($params['funcs']) )
				echo '<tr class="tbl-linha sem-registros"><td colspan="3">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';

			foreach( $params['funcs'] as $l ): ?>
				<tr class="tbl-linha">
					<td headers="th-id" class="tbl-celula-id">
						<input type="checkbox" name="id[]" value="<?= $l['VALOR']; ?>"/>
					</td>
					<td headers="th-descr"><?= $l['TEXTO']; ?></td>
					<td headers="th-opcoes" class="tbl-celula-opcoes">
						<a href="javascript:;" onclick="SelecionarLinha(this, true); $rf.submit();" class="so-icone ico-remover">
							<?= TXT_LINK_REMOVER;?>
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
	<script>
		$rf = $('#form-remover-func')._formulario({
			depois: function(){
			$('.lista-registros :checked').parents('tr').remove();
			},
			aparencia: { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: null }
		});
	</script>
[/DL3-SCRIPTS]
