<?php
/**
 * Created by PhpStorm.
 * User: dlepera
 * Date: 05/11/15
 * Time: 17:21
 */

!isset($params) and $params = $this->_obterparams();

?>

[DL3-CARREGANDO]
	<!-- Carregando Conteúdo -->
	<div id="dl3-carregando-conteudo" style="position: fixed; top: 0; left: 0; z-index: 3; width: 100%; height: 100%; background: #F4F7FB; text-align: center;">
		<div style="position: absolute; top: 50%; left: 50%; transform: translateY(-75%) translateX(-50%); width: 40%;">
			<img src="<?php echo \DL3::$dir_relativo . \DL3::$dir_temas . $params['carregando-tema']; ?>/css/imagens/logotipo.png" style="max-width: 20%; display: inline-block; vertical-align: middle;"/>

			<p style="display: inline-block; color: #6A8397; font-size: large;">
				Carregando o conteúdo!<br/>
				Por favor, aguarde...
			</p>
		</div>
	</div>
[/DL3-CARREGANDO]

[DL3-SCRIPTS]
	<script>
		//<![CDATA[
		$(window).on('load', function(){
			var $cont = $('#dl3-carregando-conteudo');
			var $paragr = $cont.find('> div');

			$paragr.animate({ left: '-=10%' }, 500, function(){
				$paragr.animate({ left: '150%' }, 650, function(){
					$cont.fadeOut(100, function(){
						$(this).remove();
					});
				});
			});
		});
		//]]>
	</script>
[/DL3-SCRIPTS]
