<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 03/02/2015 11:35:30
 */

if( !isset($params) )
    $params = $this->_obterparams();

?>

[DL3-CONTEUDO]
    <div class="albuns">
        <?php foreach( $params['lista'] as $l ): ?>
        <a href="albuns-de-fotos/fotos/<?= $l['album_id']; ?>">
            <figure class="album-info">
                <img src="./<?= $l['foto_album_imagem']; ?>" alt="<?= $l['album_nome']; ?>" class="album-capa"/>

                <figcaption>
                    <span class="album-titulo"><?= $l['album_nome']; ?></span><br/>
                    <span class="album-data"><?= \Funcoes::_formatardatahora($l['log_registro_data_criacao'], 'd/m/Y H:i'); ?></span>
                </figcaption>
            </figure>
        </a>
        <?php endforeach; ?>
    </div>
[/DL3-CONTEUDO]