<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 03/02/2015 12:36:09
 */

!isset($params) and $params = $this->_obterparams();

?>
[DL3-CONTEUDO]
    <div id="album" class="widget"></div>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $('#album')._dlgaleria({
        minis: true,
        naveg: true,
        fotos: [
            <?php foreach( $params['fotos'] as $f ): ?>
            { src: './<?= $f['foto_album_imagem']; ?>', titulo: '<?= $f['foto_album_titulo']; ?>', descr: '<?= $f['foto_album_descr']; ?>' },
            <?php endforeach; ?>
        ]
    });
</script>
[/DL3-SCRIPTS]