<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) AND $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_GRUPO; ?></legend>

            <p class="form-paragr">
                <label for="txt-descr" class="form-rotulo"><?= TXT_ROTULO_DESCR; ?>:</label><br/>
                <input type="text" name="descr" id="txt-descr" value="<?= $mod->descr; ?>" class="form-controle" required/>
            </p>

            <p class="form-paragr">
                <span class="form-rotulo"><?= TXT_ROTULO_PUBLICAR; ?></span><br/>
                <input type="checkbox" name="publicar" id="chk-publicar" class="form-alternar"<?php $mod->publicar AND print(' CHECKED'); ?>/>
                <label for="chk-publicar"></label>
            </p>
        </fieldset>

        <?php if( $params['mostrar-perms?'] ): ?>
        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_PERMISSOES; ?></legend>

            <ul class="grp-funcs">
                <?php
                    foreach( $params['menu-modulos'] as $mm ):
                        $sm_k = array_keys(preg_grep(
                                "~^{$mm['modulo_id']}$~",
                                array_column($params['sub-modulos'], 'modulo_pai')
                        ));

                        if( count($sm_k) > 0 ): ?>
                        <li class="grp-modulo">
                            <p class="grp-nm-modulo"><?= $mm['modulo_nome']; ?></p>

                            <?php foreach( $sm_k as $k1 ):
                                $sm     = $params['sub-modulos'][$k1];
                                $fc_k   = array_keys(preg_grep(
                                    "~^{$sm['modulo_id']}$~",
                                    array_column($params['funcs'], 'func_modulo')
                                ));

                                if( count($fc_k) > 0 ): ?>
                                <p class="grp-nm-submodulo"><?= $sm['modulo_nome']; ?><p>

                                <ul class="grp-submodulo flexivel">
                                    <?php foreach( $fc_k as $k2 ):
                                        $fc = $params['funcs'][$k2]; ?>
                                        <li class="grp-func col-3">
                                            <input type="checkbox" name="funcs[]" id="func-mod-<?= $fc['func_modulo_id']; ?>" value="<?= $fc['func_modulo_id']; ?>"
                                                <?php in_array($fc['func_modulo_id'], $mod->funcs) AND print(' CHECKED'); ?>/>
                                            <label for="func-mod-<?= $fc['func_modulo_id']; ?>"><?= $fc['func_modulo_descr']; ?></label>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>

                                <input type="checkbox" id="selc-todos-<?= $k1; ?>"<?php !$params['incluindo'] AND print(' CHECKED'); ?>/>
                                <label for="selc-todos-<?= $k1; ?>" class="form-rotulo"><?= TXT_ROTULO_SELECIONAR_TODOS; ?></label>
                                <?php endif;
                            endforeach; ?>
                        </li>
                        <?php endif;
                    endforeach;
                ?>
            </ul>
        </fieldset>
        <?php endif;

        if( !$params['incluindo'] ): ?>
        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_MEMBROS; ?></legend>

            <table class="lista-registros">
                <thead class="tbl-titulos">
                    <tr class="tbl-linha">
                        <th id="th-nome"><?= TXT_LISTA_TITULO_NOME; ?></th>
                    </tr>
                </thead>

                <tbody class="tbl-conteudo">
                    <?php if( !count($params['membros']) )
                        echo '<tr class="tbl-linha sem-registros"><td>', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';

                    foreach( $params['membros'] as $l ): ?>
                    <tr class="tbl-linha">
                        <td headers="th-nome"><?= $l['usuario_info_nome']; ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </fieldset>
        <?php endif; ?>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    // Selecionar todos os checkbox de um determinado sub-módulo
    $(':checkbox[id^="selc-todos-"]').on('change', function(){
        $(this).each(function(){
            var $th = $(this);
            var chk = this.checked;

            $th.prev().find(':checkbox').each(function(){
                this.checked = chk;
            });
        });
    });

    $('.grp-submodulo :checkbox').not(':checked').parents('.grp-submodulo').each(function(){
        $(this).next()[0].checked = false;
    });
    //]]>
</script>
[/DL3-SCRIPTS]