<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

!isset($params) and $params = $this->_obterparams();

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/titulo_h2.phtml'; ?>

    <?php if( $params['msg-usuario-bloq?'] ): ?>
    <p class="msg-atencao"><?= MSG_USUARIO_BLOQUEADO; ?></p>
    <?php endif;

    /*
     * TAREFA: Carregar a foto sem precisar recarregar a página
     */
    if( !$params['inserindo'] ): ?>
	<form id="form-foto-perfil" action="admin/usuarios/salvar-foto" enctype="multipart/form-data" class="usr-alterar-foto">
		<input type="hidden" name="id" value="<?= $mod->id; ?>"/>

		<?php if( $params['usuario-logado?'] ): ?>
			<input type="file" name="perfil_foto" id="perfil-foto" class="form-controle"/>
			<label for="perfil-foto">
				<?= $mod->_mostrarfoto(\DL3::$dir_relativo, 'g'); ?>
				<span class="msg-alterar-foto"><?= MSG_USUARIO_ALTERAR_FOTO; ?></span>
			</label>
		<?php else:
			echo $mod->_mostrarfoto(\DL3::$dir_relativo, 'g');
		endif; ?>
	</form>
	<?php endif; ?>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?= $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_DADOS_PESSOAIS; ?></legend>

            <p class="form-paragr">
                <label for="info-nome" class="form-rotulo"><?= TXT_ROTULO_NOME; ?>:</label><br/>
                <input type="text" name="info_nome" id="info-nome" value="<?= $mod->info_nome; ?>" class="form-controle" required/>
            </p>

            <p class="form-paragr">
                <label for="info-email" class="form-rotulo"><?= TXT_ROTULO_EMAIL; ?>:</label><br/>
                <input type="email" name="info_email" id="info-email" value="<?= $mod->info_email; ?>" class="form-controle" required/>
            </p>

            <p class="form-paragr">
                <label for="info-telefone"><?= TXT_ROTULO_TELEFONE; ?>:</label><br/>

	            <span class="form-dica">
	                <!-- Alternar a mácara do telefone -->
	                <input type="checkbox" id="alt-mask-fone" data-telefone="#info-telefone"<?php strlen($mod->info_telefone) === 16 and print(' CHECKED'); ?>/>
	                <label for="alt-mask-fone"><?= TXT_ROTULO_ALT_MASK_FONE; ?></label><br/>
	            </span>

                <input type="tel" name="info_telefone" id="info-telefone" pattern="<?= \Funcoes::_expreg_form(EXPREG_TELEFONE_GERAL); ?>" value="<?= $mod->info_telefone; ?>" class="form-controle"/>
            </p>

            <p class="form-paragr">
                <span class="form-rotulo"><?= TXT_ROTULO_SEXO; ?>:</span><br/>
                <input type="radio" name="info_sexo" id="info-sexo-m" value="M"<?php $mod->info_sexo == 'M' and print(' CHECKED'); ?>/>

                <label for="info-sexo-m"><?= TXT_OPCAO_MASCULINO; ?></label>

                <input type="radio" name="info_sexo" id="info-sexo-f" value="F"<?php $mod->info_sexo == 'F' and print(' CHECKED'); ?>/>
                <label for="info-sexo-f"><?= TXT_OPCAO_FEMININO; ?></label>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_PREFERENCIAS; ?></legend>

            <p class="form-paragr">
                <label for="pref-idioma" class="form-rotulo"><?= TXT_ROTULO_IDIOMA; ?>:</label><br/>
                <select name="pref_idioma" id="pref-idioma" class="form-controle" required>
                    <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>

                    <?php foreach( $params['idiomas'] as $o ): ?>
                    <option value="<?= $o['VALOR']; ?>"<?php $mod->pref_idioma == $o['VALOR'] and print(' SELECTED'); ?>>
                        <?= $o['TEXTO']; ?>
                    </option>
                    <?php endforeach; ?>
                </select>

                <?php if( $params['novo-idioma?'] ): ?>
                <a href="javascript:;" onclick="CarregarForm('desenvolvedor/idiomas/novo', null, function(){ CarregarSelect($('#pref-idioma'), 'desenvolvedor/idiomas/carregar-select'); });" class="com-icone ico-inserir ico-select">
                    <?= TXT_LINK_NOVO_IDIOMA; ?>
                </a>
                <?php endif; ?>
            </p>

            <p class="form-paragr">
                <label for="pref-tema" class="form-rotulo"><?= TXT_ROTULO_TEMA; ?>:</label><br/>
                <select name="pref_tema" id="pref-tema" class="form-controle" required>
                    <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>

                    <?php foreach( $params['temas'] as $o ): ?>
                    <option value="<?= $o['VALOR']; ?>"<?php $mod->pref_tema == $o['VALOR'] and print(' SELECTED'); ?>>
                        <?= $o['TEXTO']; ?>
                    </option>
                    <?php endforeach; ?>
                </select>

                <?php if( $params['novo-tema?'] ): ?>
                <a href="javascript:;" onclick="CarregarForm('desenvolvedor/temas/novo', null, function(){ CarregarSelect($('#pref-tema'), 'desenvolvedor/temas/carregar-select'); });" class="com-icone ico-inserir ico-select">
                    <?= TXT_LINK_NOVO_TEMA; ?>
                </a>
                <?php endif; ?>
            </p>

            <p class="form-paragr">
                <label for="pref-formato-data" class="form-rotulo"><?= TXT_ROTULO_FORMATO_DATA; ?>:</label><br/>
                <select name="pref_formato_data" id="pref-formato-data" class="form-controle" required>
                    <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>

                    <?php foreach( $params['formatos-data'] as $o ): ?>
                    <option value="<?= $o['VALOR']; ?>"<?php $mod->pref_formato_data == $o['VALOR'] and print(' SELECTED'); ?>>
                        <?= $o['TEXTO']; ?>
                    </option>
                    <?php endforeach; ?>
                </select>
            </p>

            <p class="form-paragr">
                <label for="pref-num-registros" class="form-rotulo"><?= TXT_ROTULO_NUM_REGISTROS; ?>:</label><br/>
                <span class="form-dica"><?= MSG_DICA_USUARIO_NUM_REGISTROS; ?></span><br/>
                <input type="number" name="pref_num_registros" id="pref-num-registros" value="<?= $mod->pref_num_registros; ?>" min="5" max="999" class="form-controle form-numero"/>
            </p>

            <p class="form-paragr">
                <span class="form-rotulo"><?= TXT_ROTULO_EXIBIR_ID; ?></span><br/>
                <span class="form-dica"><?= TXT_DICA_EXIBIR_ID; ?></span><br/>
                <input type="checkbox" name="pref_exibir_id" id="chk-exibir-id" class="form-alternar"<?php $mod->pref_exibir_id and print(' CHECKED'); ?>/>
                <label for="chk-exibir-id"></label>
            </p>

            <p class="form-paragr">
                <span class="form-rotulo"><?= TXT_ROTULO_FILTRO_MENU; ?></span><br/>
                <span class="form-dica"><?= TXT_DICA_FILTRO_MENU; ?></span><br/>
                <input type="checkbox" name="pref_filtro_menu" id="chk-filtro-menu" class="form-alternar"<?php $mod->pref_filtro_menu and print(' CHECKED'); ?>/>
                <label for="chk-filtro-menu"></label>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?= TXT_LEGENDA_ACESSO_SISTEMA; ?></legend>

            <?php if( $params['incluindo'] || !$params['usuario-logado?'] ): ?>
            <p class="form-paragr">
                <label for="info-grupo" class="form-rotulo"><?= TXT_ROTULO_GRUPO; ?>:</label><br/>
                <select name="info_grupo" id="info-grupo" class="form-controle" required>
                    <option value=""><?= TXT_OPCAO_SELECIONE_UMA_OPCAO; ?></option>

                    <?php foreach( $params['grupos-usuarios'] as $o ): ?>
                    <option value="<?= $o['VALOR']; ?>"<?php $mod->info_grupo == $o['VALOR'] || ($params['incluindo'] && $mod->padrao) and print(' SELECTED'); ?>>
                        <?= $o['TEXTO']; ?>
                    </option>
                    <?php endforeach; ?>
                </select>

                <?php if( $params['novo-grupo?'] ): ?>
                <a href="javascript:;" onclick="CarregarForm('admin/grupos-de-usuarios/novo', null, function(){ CarregarSelect($('#info-grupo'), 'admin/grupos-de-usuarios/carregar-select'); });" class="com-icone ico-inserir ico-select">
                    <?= TXT_LINK_NOVO_GRUPO_USUARIO; ?>
                </a>
                <?php endif; ?>
            </p>
            <?php elseif( $params['usuario-logado?'] ): ?>
            <p class="form-paragr">
                <?= TXT_ROTULO_GRUPO, ':<br/>', $params['grupo-descr']; ?>
                <input type="hidden" name="info_grupo" value="<?= $mod->info_grupo; ?>"/>
            </p>
            <?php endif;

            if( $params['incluindo'] ): ?>
            <p class="form-paragr">
                <label for="info-login" class="form-rotulo"><?= TXT_ROTULO_LOGIN; ?>:</label><br/>
                <input type="text" name="info_login" id="info-login" class="form-controle" required/>
            </p>

            <p class="form-paragr">
                <label for="info-senha" class="form-rotulo"><?= TXT_ROTULO_SENHA; ?>:</label><br/>
                <input type="password" name="info_senha" id="info-senha" class="form-controle" required/>
            </p>

            <p class="form-paragr">
                <label for="conf-senha" class="form-rotulo"><?= TXT_ROTULO_CONF_SENHA; ?>:</label><br/>
                <input type="password" name="info_senha_conf" id="conf-senha" class="form-controle" required/>
            </p>
            <?php else: ?>
            <p class="form-paragr">
                <label for="info-login" class="form-rotulo"><?= TXT_ROTULO_LOGIN; ?>:</label><br/>
                <input type="text" name="info_login" id="info-login" value="<?= $mod->info_login; ?>" class="form-controle" readonly required/>
            </p>
            <?php endif;

            if( !$params['usuario-logado?'] ): ?>
            <p class="form-paragr">
                <input type="checkbox" name="conf_reset" id="conf-reset"<?php $mod->conf_reset and print(' CHECKED'); ?>/>
                <label for="conf-reset"><?= TXT_ROTULO_RESET; ?></label><br/>
                <span class="form-dica"><?= MSG_DICA_USUARIO_RESET; ?></span>
            </p>

            <p class="form-paragr">
                <input type="checkbox" name="conf_bloq" id="conf-bloq"<?php $mod->conf_bloq  and print(' CHECKED'); ?>/>
                <label for="conf-bloq"><?= TXT_ROTULO_BLOQ; ?></label><br/>
                <span class="form-dica"><?= MSG_DICA_USUARIO_BLOQ; ?></span>
            </p>
            <?php endif; ?>
        </fieldset>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $('#info-telefone')._mascara('<?= strlen($mod->info_fone) === 14 || $params['incluindo'] ? MASK_TELEFONE_CELULAR_8 : MASK_TELEFONE_CELULAR_9; ?>');

    $('#alt-mask-fone').on('change',
	    { msk8: '<?= MASK_TELEFONE_CELULAR_8; ?>', msk9: '<?= MASK_TELEFONE_CELULAR_9; ?>' },
	    AlternarMaskFone
    );

    $('#form-foto-perfil')._formulario({
	    depois      : function(){ window.location.reload(); },
	    aparencia   : { tema: '<?= \DL3::$plugin_formulario_tema; ?>', estilo: null }
    }).find(':file').on('change', function(){ $(this).parents('form').submit(); });
    //]]>
</script>
[/DL3-SCRIPTS]

[DL3-HEAD]
[/DL3-HEAD]
