<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 10/01/2015 11:14:18
 */

if( !isset($params) )
    $params = $this->_obterparams();

?>

[DL3-CONTEUDO]
    <p class="msg-info"><?= MSG_RESET_SENHA_PROX_LOGIN; ?></p>

    <form id="form-<?= $params['form-id']; ?>" method="post" action="<?= preg_replace('~^[a-z0-9A-Z]+/~', 'admin/', $params['form-action']); ?>">
        <p class="form-paragr">
            <label for="senha-atual" class="form-rotulo"><?= TXT_ROTULO_SENHA_ATUAL; ?>:</label><br/>
            <input type="password" name="senha_atual" id="senha-atual" class="form-controle" required/>
        </p>

        <p class="form-paragr">
            <label for="senha-nova" class="form-rotulo"><?= TXT_ROTULO_SENHA_NOVA; ?>:</label><br/>
            <input type="password" name="senha_nova" id="senha-nova" class="form-controle" required/>
        </p>

        <p class="form-paragr">
            <label for="senha-nova-conf" class="form-rotulo"><?= TXT_ROTULO_SENHA_NOVA_CONF; ?>:</label><br/>
            <input type="password" name="senha_nova_conf" id="senha-nova-conf" class="form-controle" required/>
        </p>

        <p class="form-botoes">
            <button type="submit" class="btn-salvar"><?= TXT_BOTAO_SALVAR; ?></button>
            <button type="reset" class="btn-cancelar"><?= TXT_BOTAO_CANCELAR; ?></button>
        </p>
    </form>
[/DL3-CONTEUDO]
