<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 16:51:21
 */

!isset($params) and $params = $this->_obterparams();

?>

[DL3-CONTEUDO]
    <!-- Inserir um novo registro -->
    <?php if( $params['perm-inserir?'] ): ?>
    <a href="<?= $params['dir-lista']; ?>novo" class="com-icone ico-inserir"><?= TXT_LINK_NOVO_USUARIO; ?></a>
    <?php endif;

    include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/form_filtro.phtml'; ?>

    <form id="form-editar-lista" method="post" action="<?= $params['dir-lista']; ?>excluir-usuarios">
        <!-- Exibir a lista com os registros selecionados -->
        <table class="lista-registros">
            <thead class="tbl-titulos">
                <tr class="tbl-linha">
                    <th id="th-chk" class="tbl-celula-chk"><input type="checkbox"/></th>
                    <?php if( $params['exibir-id'] ): ?>
                    <th id="th-id" class="tbl-celula-id"><?= TXT_LISTA_TITULO_ID; ?></th>
                    <?php endif; ?>

                    <th id="th-grupo" class="v-desk"><?= TXT_LISTA_TITULO_GRUPO; ?></th>
                    <th id="th-nome"><?= TXT_LISTA_TITULO_NOME; ?></th>
                    <th id="th-email" class="v-desk"><?= TXT_LISTA_TITULO_EMAIL; ?></th>
					
                    <th id="th-opcoes" class="tbl-celula-opcoes"><?= TXT_LISTA_TITULO_OPCOES; ?></th>
                </tr>
            </thead>

            <tbody class="tbl-conteudo">
                <?php if( !count($params['lista']) )
                    echo '<tr class="tbl-linha sem-registros"><td>', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO,'</td></tr>';

                foreach( $params['lista'] as $l ): ?>
                <tr class="tbl-linha">
                    <td headers="th-chk" class="tbl-celula-chk"><input type="checkbox" name="id[]" value="<?= $l['usuario_id']; ?>"/></td>
                    <?php if( $params['exibir-id'] ): ?>
                    <td headers="th-id" class="tbl-celula-id"><?= $l['usuario_id']; ?></td>
                    <?php endif; ?>

                    <td headers="th-grupo" class="v-desk"><?= $l['grupo_usuario_descr']; ?></td>
                    <td headers="th-nome" class="tbl-celula-infos">
                        <?= $l['usuario_info_nome']; ?><br/>
	                    <span class="v-smart"><?= $l['grupo_usuario_descr']; ?></span>
                    </td>
                    <td headers="th-email" class="v-desk"><?= $l['usuario_info_email']; ?></td>

                    <td headers="th-opcoes" class="tbl-celula-opcoes">
                        <?php if( $params['perm-bloquear?'] ):
                            if( $l['usuario_conf_bloq'] == 0 ): ?>
                            <a href="javascript:" onclick="SelecionarLinha(this, true); $el._executar('<?= $params['dir-lista']; ?>bloquear-usuarios', null, function(){ window.location.reload(); });" class="so-icone ico-bloquear" title="<?= TXT_LINK_TITLE_BLOQUEAR_USUARIO; ?>">
                                <?= TXT_LINK_BLOQUEAR; ?>
                            </a>
                            <?php else: ?>
                            <a href="javascript:" onclick="SelecionarLinha(this, true); $el._executar('<?= $params['dir-lista']; ?>desbloquear-usuarios', null, function(){ window.location.reload(); });" class="so-icone ico-desbloquear" title="<?= TXT_LINK_TITLE_DESBLOQUEAR_USUARIO; ?>">
                                <?= TXT_LINK_DESBLOQUEAR; ?>
                            </a>
                            <?php endif;
                        endif;

                        if( $params['perm-editar?'] ): ?>
                        <a href="<?= $params['dir-lista']; ?>editar/<?= $l['usuario_id']; ?>" class="so-icone ico-editar" title="<?= TXT_LINK_TITLE_EDITAR; ?>">
                            <?= TXT_LINK_EDITAR; ?>
                        </a>
                        <?php endif;

                        if( $params['perm-remover?'] ): ?>
                        <a href="javascript:" onclick="SelecionarLinha(this, true); $el.submit();" class="so-icone ico-remover" title="<?= TXT_LINK_TITLE_REMOVER; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

            <tfoot class="tbl-rodape">
                <?php if( count($params['lista']) ): ?>
                <tr class="tbl-linha com-marcados">
                    <td>
                        <?php if( $params['perm-remover?'] ): ?>
                        <a href="javascript:" onclick="$el.submit();" class="so-icone ico-remover" title="<?= TXT_LINK_TITLE_REMOVER_SELECIONADOS; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif;

                        if( $params['perm-bloquear?'] ): ?>
                        <a href="javascript:" onclick="$el._executar('<?= $params['dir-lista']; ?>bloquear-usuarios', null, function(){ window.location.reload(); });" class="so-icone ico-bloquear" title="<?= TXT_LINK_TITLE_BLOQUEAR_USUARIOS_SELECIONADOS; ?>">
                            <?= TXT_LINK_BLOQUEAR; ?>
                        </a>

                        <a href="javascript:" onclick="$el._executar('<?= $params['dir-lista']; ?>desbloquear-usuarios', null, function(){ window.location.reload(); });" class="so-icone ico-desbloquear" title="<?= TXT_LINK_TITLE_DESBLOQUEAR_USUARIOS_SELECIONADOS; ?>">
                            <?= TXT_LINK_DESBLOQUEAR; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endif; ?>
            </tfoot>
        </table>
    </form>

    <div id="paginacao"></div>
[/DL3-CONTEUDO]