<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 16:51:21
 */

if( !isset($params) )
    $params = $this->_obterparams();

?>

<section class="dl3">
    <h1><?= $params['titulo']; ?></h1>

    <!-- Inserir um novo registro -->
    <?php if( $params['perm-inserir?'] ): ?>
    <a href="admin/envio-de-emails/novo" class="com-icone a-inserir"><?= TXT_LINK_NOVO_CONFIGEMAIL; ?></a>
    <?php endif; ?>

    <?php include_once 'aplicativos/'. DL3_APLICATIVO .'/comum/visoes/form_filtro.phtml'; ?>

    <form id="form-editar-lista" method="post" action="admin/envio-de-emails/excluir-configuracao">
        <!-- Exibir a lista com os registros selecionados -->
        <table class="lista">
            <thead>
                <tr>
                    <th id="th-id" class="td-id"><input type="checkbox"/></th>
                    <th id="th-titulo"><?= TXT_TABELA_TITULO; ?></th>
                    <th id="th-host" class="v-desk"><?= TXT_TABELA_HOST; ?></th>
                    <th id="th-principal"><?= TXT_TABELA_PRINCIPAL; ?></th>
                    <th id="th-opcoes" class="td-opcoes"><?= TXT_TABELA_TITULO_OPCOES; ?></th>
                </tr>
            </thead>

            <tbody>
                <?php if( !count($params['lista']) )
                    echo '<tr class="sem-registros"><td colspan="5">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO,'</td></tr>';

                foreach( $params['lista'] as $l ): ?>
                <tr>
                    <td headers="th-id" class="td-id"><input type="checkbox" name="id[]" value="<?= $l['config_email_id']; ?>"/></td>
                    <td headers="th-titulo"><?= $l['config_email_titulo']; ?></td>
                    <td headers="th-host" class="v-desk"><?= $l['config_email_host']; ?></td>
                    <td headers="th-principal"><?= $l['PRINCIPAL']; ?></td>
                    <td headers="th-opcoes" class="td-opcoes">
                        <?php if( $params['perm-testar?'] ): ?>
                        <a href="javascript:;" onclick="SelecionarLinha(this); $el.executar('admin/envio-de-emails/testar-configuracao/<?= $l['config_email_id']; ?>', null, function(){ return; });" class="com-icone a-email">
                            <?= TXT_LINK_TESTAR_CONFIGURACAO; ?>
                        </a>
                        <?php endif;

                        if( $params['perm-editar?'] ): ?>
                        <a href="admin/envio-de-emails/editar/<?= $l['config_email_id']; ?>" class="com-icone a-editar" title="<?= TXT_LINK_TITLE_EDITAR; ?>">
                            <?= TXT_LINK_EDITAR; ?>
                        </a>
                        <?php endif;

                        if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="SelecionarLinha(this); $el.submit();" class="com-icone a-remover" title="<?= TXT_LINK_TITLE_REMOVER; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>

            <tfoot>
                <?php if( count($params['lista']) ): ?>
                <tr class="com-marcados">
                    <td colspan="5">
                        <?php if( $params['perm-remover?'] ): ?>
                        <a href="javascript:;" onclick="$el.submit();" class="com-icone a-remover" title="<?= TXT_LINK_TITLE_REMOVER_SELECIONADOS; ?>">
                            <?= TXT_LINK_REMOVER; ?>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endif; ?>
            </tfoot>
        </table>
    </form>

    <div id="paginacao"></div>
</section>